# -*- coding: utf-8 -*-
from __future__ import annotations
"""
Level 1 기초 영단어 1,000개 데이터셋 구축 스크립트
교육부 권장 초등/기초 필수 영단어 1,000단어의 완전한 데이터셋을 생성하고
level_1.json, level_1_words.txt 및 manifest.json을 갱신합니다.
Python 3.9+ 호환, UTF-8 인코딩 적용
"""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SCRIPTS_DIR = Path(__file__).resolve().parent
SERVER_DIR = SCRIPTS_DIR.parent
DATA_DIR = SERVER_DIR / "data"
RAW_DIR = SERVER_DIR / "raw"

# 교육부 및 국제 기초 기준 필수 1,000 영단어 (단어, 품사, 대표 한국어 뜻)
RAW_WORDS_1000: list[tuple[str, str, str]] = [
    # 1-50 (대명사 / 접속사 / Be동사 / 기본 전치사)
    ("I", "pronoun", "나, 저"),
    ("you", "pronoun", "너, 당신, 너희들"),
    ("he", "pronoun", "그, 그 사람"),
    ("she", "pronoun", "그녀"),
    ("it", "pronoun", "그것"),
    ("we", "pronoun", "우리"),
    ("they", "pronoun", "그들, 그것들"),
    ("this", "pronoun", "이것, 이 사람"),
    ("that", "pronoun", "저것, 그 사람"),
    ("these", "pronoun", "이것들"),
    ("those", "pronoun", "저것들"),
    ("what", "pronoun", "무엇, 무슨"),
    ("who", "pronoun", "누구"),
    ("where", "adverb", "어디에"),
    ("when", "adverb", "언제"),
    ("why", "adverb", "왜, 어째서"),
    ("how", "adverb", "어떻게, 얼마나"),
    ("all", "determiner", "모든, 전부"),
    ("some", "determiner", "몇몇의, 어떤"),
    ("any", "determiner", "어떤, 조금의"),
    ("many", "determiner", "많은"),
    ("much", "determiner", "많은, 많이"),
    ("every", "determiner", "모든, 매-"),
    ("other", "adjective", "다른"),
    ("same", "adjective", "같은, 동일한"),
    ("and", "conjunction", "그리고, 와/과"),
    ("but", "conjunction", "하지만, 그러나"),
    ("or", "conjunction", "또는, 아니면"),
    ("so", "conjunction", "그래서, 아주"),
    ("because", "conjunction", "왜냐하면, ~때문에"),
    ("if", "conjunction", "만약 ~라면"),
    ("as", "conjunction", "~처럼, ~로서"),
    ("at", "preposition", "~에, ~에서"),
    ("in", "preposition", "~안에, ~에서"),
    ("on", "preposition", "~위에, ~에"),
    ("to", "preposition", "~로, ~에게"),
    ("for", "preposition", "~를 위해, ~동안"),
    ("from", "preposition", "~로부터, ~에서"),
    ("with", "preposition", "~와 함께"),
    ("by", "preposition", "~에 의해, ~옆에"),
    ("of", "preposition", "~의, ~중에서"),
    ("about", "preposition", "~에 대하여, 약"),
    ("into", "preposition", "~안으로"),
    ("over", "preposition", "~너머에, ~위에"),
    ("under", "preposition", "~아래에"),
    ("after", "preposition", "~후에, 뒤에"),
    ("before", "preposition", "~전에, 앞에"),
    ("between", "preposition", "~사이에"),
    ("through", "preposition", "~을 통하여"),
    ("without", "preposition", "~없이"),

    # 51-100 (숫자 / 시간 / 날짜 / 계절)
    ("one", "number", "하나, 일"),
    ("two", "number", "둘, 이"),
    ("three", "number", "셋, 삼"),
    ("four", "number", "넷, 사"),
    ("five", "number", "다섯, 오"),
    ("six", "number", "여섯, 육"),
    ("seven", "number", "일곱, 칠"),
    ("eight", "number", "여덟, 팔"),
    ("nine", "number", "아홉, 구"),
    ("ten", "number", "열, 십"),
    ("eleven", "number", "열하나"),
    ("twelve", "number", "열둘"),
    ("thirteen", "number", "열셋"),
    ("fourteen", "number", "열넷"),
    ("fifteen", "number", "열다섯"),
    ("twenty", "number", "스물, 이십"),
    ("thirty", "number", "서른, 삼십"),
    ("forty", "number", "마흔, 사십"),
    ("fifty", "number", "쉰, 오십"),
    ("hundred", "number", "백"),
    ("thousand", "number", "천"),
    ("first", "adjective", "첫 번째의"),
    ("second", "adjective", "두 번째의, 초"),
    ("third", "adjective", "세 번째의"),
    ("time", "noun", "시간, 때"),
    ("day", "noun", "날, 하루, 낮"),
    ("week", "noun", "주, 일주일"),
    ("month", "noun", "달, 월"),
    ("year", "noun", "해, 년"),
    ("today", "noun", "오늘"),
    ("tomorrow", "noun", "내일"),
    ("yesterday", "noun", "어제"),
    ("morning", "noun", "아침, 오전"),
    ("afternoon", "noun", "오후"),
    ("evening", "noun", "저녁"),
    ("night", "noun", "밤, 야간"),
    ("hour", "noun", "시간, 1시간"),
    ("minute", "noun", "분, 잠깐"),
    ("clock", "noun", "시계"),
    ("calendar", "noun", "달력"),
    ("spring", "noun", "봄, 샘"),
    ("summer", "noun", "여름"),
    ("autumn", "noun", "가을"),
    ("winter", "noun", "겨울"),
    ("season", "noun", "계절, 시기"),
    ("Sunday", "noun", "일요일"),
    ("Monday", "noun", "월요일"),
    ("Tuesday", "noun", "화요일"),
    ("Wednesday", "noun", "수요일"),
    ("Thursday", "noun", "목요일"),

    # 101-150 (가족 / 사람 / 신체)
    ("Friday", "noun", "금요일"),
    ("Saturday", "noun", "토요일"),
    ("person", "noun", "사람, 개인"),
    ("people", "noun", "사람들, 국민"),
    ("man", "noun", "남자, 사람"),
    ("woman", "noun", "여자, 여성"),
    ("boy", "noun", "소년, 남자아이"),
    ("girl", "noun", "소녀, 여자아이"),
    ("baby", "noun", "아기, 갓난아이"),
    ("child", "noun", "어린이, 아이"),
    ("children", "noun", "아이들"),
    ("parent", "noun", "부모"),
    ("father", "noun", "아버지"),
    ("mother", "noun", "어머니"),
    ("dad", "noun", "아빠"),
    ("mom", "noun", "엄마"),
    ("son", "noun", "아들"),
    ("daughter", "noun", "딸"),
    ("brother", "noun", "형제, 오빠, 남동생"),
    ("sister", "noun", "자매, 언니, 여동생"),
    ("grandfather", "noun", "할아버지"),
    ("grandmother", "noun", "할머니"),
    ("uncle", "noun", "삼촌, 이모부, 고모부"),
    ("aunt", "noun", "이모, 고모, 숙모"),
    ("cousin", "noun", "사촌"),
    ("friend", "noun", "친구"),
    ("neighbor", "noun", "이웃"),
    ("body", "noun", "몸, 신체"),
    ("head", "noun", "머리, 우두머리"),
    ("hair", "noun", "머리카락, 털"),
    ("face", "noun", "얼굴, 마주하다"),
    ("eye", "noun", "눈"),
    ("ear", "noun", "귀"),
    ("nose", "noun", "코"),
    ("mouth", "noun", "입"),
    ("lip", "noun", "입술"),
    ("tooth", "noun", "이, 치아"),
    ("teeth", "noun", "이들(복수)"),
    ("neck", "noun", "목"),
    ("shoulder", "noun", "어깨"),
    ("arm", "noun", "팔, 무기"),
    ("hand", "noun", "손, 건네다"),
    ("finger", "noun", "손가락"),
    ("thumb", "noun", "엄지손가락"),
    ("chest", "noun", "가슴, 상자"),
    ("back", "noun", "등, 뒤, 돌아가다"),
    ("leg", "noun", "다리"),
    ("knee", "noun", "무릎"),
    ("foot", "noun", "발, 피트(단위)"),
    ("feet", "noun", "발들(복수)"),

    # 151-200 (신체 / 감각 / 건강 / 음식)
    ("toe", "noun", "발가락"),
    ("skin", "noun", "피부, 껍질"),
    ("heart", "noun", "심장, 마음"),
    ("blood", "noun", "피, 혈액"),
    ("bone", "noun", "뼈"),
    ("voice", "noun", "목소리, 음성"),
    ("health", "noun", "건강"),
    ("sick", "adjective", "아픈, 병든"),
    ("ill", "adjective", "아픈, 나쁜"),
    ("pain", "noun", "고통, 통증"),
    ("medicine", "noun", "약, 의학"),
    ("doctor", "noun", "의사, 박사"),
    ("nurse", "noun", "간호사"),
    ("hospital", "noun", "병원"),
    ("food", "noun", "음식, 식량"),
    ("water", "noun", "물"),
    ("milk", "noun", "우유"),
    ("juice", "noun", "주스, 즙"),
    ("tea", "noun", "차"),
    ("coffee", "noun", "커피"),
    ("bread", "noun", "빵"),
    ("rice", "noun", "쌀, 밥"),
    ("meat", "noun", "고기"),
    ("beef", "noun", "소고기"),
    ("pork", "noun", "돼지고기"),
    ("chicken", "noun", "닭, 닭고기"),
    ("fish", "noun", "물고기, 생선"),
    ("egg", "noun", "달걀, 알"),
    ("cheese", "noun", "치즈"),
    ("butter", "noun", "버터"),
    ("sugar", "noun", "설탕"),
    ("salt", "noun", "소금"),
    ("pepper", "noun", "후추, 고추"),
    ("soup", "noun", "수프, 국"),
    ("salad", "noun", "샐러드"),
    ("sandwich", "noun", "샌드위치"),
    ("cake", "noun", "케이크"),
    ("cookie", "noun", "쿠키, 과자"),
    ("candy", "noun", "사탕"),
    ("chocolate", "noun", "초콜릿"),
    ("ice", "noun", "얼음"),
    ("ice cream", "noun", "아이스크림"),
    ("fruit", "noun", "과일, 열매"),
    ("apple", "noun", "사과"),
    ("banana", "noun", "바나나"),
    ("orange", "noun", "오렌지, 주황색"),
    ("grape", "noun", "포도"),
    ("strawberry", "noun", "딸기"),
    ("lemon", "noun", "레몬"),
    ("watermelon", "noun", "수박"),

    # 201-250 (음식 / 식사 / 주거 / 집)
    ("vegetable", "noun", "채소, 야채"),
    ("tomato", "noun", "토마토"),
    ("potato", "noun", "감자"),
    ("carrot", "noun", "당근"),
    ("onion", "noun", "양파"),
    ("meal", "noun", "식사, 끼니"),
    ("breakfast", "noun", "아침 식사"),
    ("lunch", "noun", "점심 식사"),
    ("dinner", "noun", "저녁 식사, 만찬"),
    ("restaurant", "noun", "식당, 레스토랑"),
    ("cafe", "noun", "카페, 찻집"),
    ("menu", "noun", "메뉴, 식단표"),
    ("cup", "noun", "컵, 잔"),
    ("glass", "noun", "유리잔, 유리"),
    ("plate", "noun", "접시"),
    ("dish", "noun", "접시, 요리"),
    ("bowl", "noun", "그릇, 사발"),
    ("spoon", "noun", "숟가락"),
    ("fork", "noun", "포크"),
    ("knife", "noun", "칼"),
    ("bottle", "noun", "병"),
    ("house", "noun", "집, 주택"),
    ("home", "noun", "가정, 집"),
    ("apartment", "noun", "아파트"),
    ("room", "noun", "방, 공간"),
    ("door", "noun", "문"),
    ("window", "noun", "창문"),
    ("wall", "noun", "벽, 담"),
    ("floor", "noun", "바닥, 층"),
    ("roof", "noun", "지붕"),
    ("ceiling", "noun", "천장"),
    ("kitchen", "noun", "주방, 부엌"),
    ("bathroom", "noun", "욕실, 화장실"),
    ("bedroom", "noun", "침실"),
    ("living room", "noun", "거실"),
    ("garden", "noun", "정원, 뜰"),
    ("yard", "noun", "마당, 야드"),
    ("gate", "noun", "대문, 출입구"),
    ("fence", "noun", "울타리"),
    ("key", "noun", "열쇠, 핵심"),
    ("bed", "noun", "침대"),
    ("table", "noun", "탁자, 식탁, 표"),
    ("chair", "noun", "의자"),
    ("desk", "noun", "책상"),
    ("sofa", "noun", "소파"),
    ("lamp", "noun", "램프, 등"),
    ("mirror", "noun", "거울"),
    ("shelf", "noun", "선반"),
    ("curtain", "noun", "커튼"),
    ("blanket", "noun", "담요"),

    # 251-300 (가전 / 옷 / 패션)
    ("pillow", "noun", "베개"),
    ("towel", "noun", "수건"),
    ("soap", "noun", "비누"),
    ("brush", "noun", "솔, 빗, 붓"),
    ("trash", "noun", "쓰레기"),
    ("telephone", "noun", "전화기"),
    ("phone", "noun", "전화, 휴대폰"),
    ("television", "noun", "텔레비전"),
    ("radio", "noun", "라디오"),
    ("computer", "noun", "컴퓨터"),
    ("internet", "noun", "인터넷"),
    ("camera", "noun", "카메라, 사진기"),
    ("clothes", "noun", "옷, 의복"),
    ("shirt", "noun", "셔츠"),
    ("t-shirt", "noun", "티셔츠"),
    ("pants", "noun", "바지"),
    ("jeans", "noun", "청바지"),
    ("dress", "noun", "드레스, 원피스, 옷을 입다"),
    ("skirt", "noun", "치마, 스커트"),
    ("suit", "noun", "정장, 어울리다"),
    ("coat", "noun", "코트, 외투"),
    ("jacket", "noun", "재킷"),
    ("sweater", "noun", "스웨터"),
    ("hat", "noun", "모자(챙 있는)"),
    ("cap", "noun", "모자(야구모자 등)"),
    ("shoes", "noun", "신발"),
    ("shoe", "noun", "신발 한 짝"),
    ("socks", "noun", "양말"),
    ("boots", "noun", "부츠, 장화"),
    ("glove", "noun", "장갑"),
    ("scarf", "noun", "스카프, 목도리"),
    ("belt", "noun", "벨트, 허리띠"),
    ("tie", "noun", "넥타이, 묶다"),
    ("pocket", "noun", "주머니"),
    ("button", "noun", "단추, 버튼"),
    ("zipper", "noun", "지퍼"),
    ("glasses", "noun", "안경"),
    ("sunglasses", "noun", "선글라스"),
    ("watch", "noun", "손목시계, 지켜보다"),
    ("ring", "noun", "반지, 울리다"),
    ("umbrella", "noun", "우산"),
    ("bag", "noun", "가방, 자루"),
    ("wallet", "noun", "지갑"),
    ("backpack", "noun", "배낭, 책가방"),
    ("school", "noun", "학교"),
    ("student", "noun", "학생"),
    ("teacher", "noun", "선생님, 교사"),
    ("class", "noun", "수업, 학급, 반"),
    ("classroom", "noun", "교실"),
    ("lesson", "noun", "수업, 교훈"),

    # 301-350 (학교 / 학용품 / 교육)
    ("book", "noun", "책, 도서"),
    ("notebook", "noun", "공책, 노트북"),
    ("paper", "noun", "종이, 신문"),
    ("pen", "noun", "펜"),
    ("pencil", "noun", "연필"),
    ("eraser", "noun", "지우개"),
    ("ruler", "noun", "자, 지배자"),
    ("crayon", "noun", "크레용"),
    ("scissors", "noun", "가위"),
    ("glue", "noun", "풀, 접착제"),
    ("board", "noun", "칠판, 게시판, 탑승하다"),
    ("chalk", "noun", "분필"),
    ("desk", "noun", "책상"),
    ("library", "noun", "도서관"),
    ("homework", "noun", "숙제"),
    ("exam", "noun", "시험"),
    ("test", "noun", "시험, 검사, 테스트하다"),
    ("grade", "noun", "학년, 성적, 등급"),
    ("score", "noun", "점수, 득점"),
    ("question", "noun", "질문, 문제"),
    ("answer", "noun", "대답, 정답, 대답하다"),
    ("problem", "noun", "문제, 곤란"),
    ("word", "noun", "단어, 낱말, 말"),
    ("sentence", "noun", "문장, 판결"),
    ("story", "noun", "이야기, 층"),
    ("page", "noun", "페이지, 쪽"),
    ("letter", "noun", "편지, 글자"),
    ("number", "noun", "숫자, 번호"),
    ("subject", "noun", "과목, 주제, 대상"),
    ("math", "noun", "수학"),
    ("science", "noun", "과학"),
    ("history", "noun", "역사"),
    ("art", "noun", "미술, 예술"),
    ("music", "noun", "음악"),
    ("English", "noun", "영어, 영국의"),
    ("Korean", "noun", "한국어, 한국의"),
    ("gym", "noun", "체육관"),
    ("playground", "noun", "운동장, 놀이터"),
    ("study", "verb", "공부하다, 연구하다"),
    ("learn", "verb", "배우다, 익히다"),
    ("teach", "verb", "가르치다"),
    ("read", "verb", "읽다"),
    ("write", "verb", "쓰다, 작성하다"),
    ("draw", "verb", "그리다, 당기다"),
    ("paint", "verb", "페인트칠하다, 그리다"),
    ("sing", "verb", "노래하다"),
    ("dance", "verb", "춤추다"),
    ("play", "verb", "놀다, 연주하다, 경기하다"),
    ("game", "noun", "게임, 경기"),
    ("toy", "noun", "장난감"),

    # 351-400 (스포츠 / 취미 / 도시 / 장소)
    ("doll", "noun", "인형"),
    ("ball", "noun", "공, 무도회"),
    ("sport", "noun", "스포츠, 운동"),
    ("soccer", "noun", "축구"),
    ("baseball", "noun", "야구"),
    ("basketball", "noun", "농구"),
    ("volleyball", "noun", "배구"),
    ("tennis", "noun", "테니스"),
    ("swimming", "noun", "수영"),
    ("running", "noun", "달리기"),
    ("bike", "noun", "자전거"),
    ("bicycle", "noun", "자전거"),
    ("hobby", "noun", "취미"),
    ("movie", "noun", "영화"),
    ("cinema", "noun", "영화관"),
    ("theater", "noun", "극장, 공연장"),
    ("museum", "noun", "박물관, 미술관"),
    ("zoo", "noun", "동물원"),
    ("park", "noun", "공원, 주차하다"),
    ("bench", "noun", "벤치, 긴 의자"),
    ("city", "noun", "도시"),
    ("town", "noun", "마을, 읍"),
    ("village", "noun", "시골 마을, 부락"),
    ("country", "noun", "나라, 국가, 시골"),
    ("world", "noun", "세계, 세상"),
    ("street", "noun", "거리, 도로"),
    ("road", "noun", "길, 도로"),
    ("way", "noun", "길, 방법, 방식"),
    ("bridge", "noun", "다리, 교량"),
    ("corner", "noun", "모퉁이, 구석"),
    ("building", "noun", "건물, 빌딩"),
    ("shop", "noun", "상점, 가게, 쇼핑하다"),
    ("store", "noun", "가게, 저장하다"),
    ("market", "noun", "시장"),
    ("supermarket", "noun", "슈퍼마켓"),
    ("bank", "noun", "은행, 둑"),
    ("post office", "noun", "우체국"),
    ("police", "noun", "경찰"),
    ("fire station", "noun", "소방서"),
    ("station", "noun", "역, 정류장"),
    ("airport", "noun", "공항"),
    ("hotel", "noun", "호텔"),
    ("farm", "noun", "농장, 농원"),
    ("factory", "noun", "공장"),
    ("office", "noun", "사무실, 직무"),
    ("church", "noun", "교회"),
    ("temple", "noun", "사원, 절"),
    ("castle", "noun", "성"),
    ("tower", "noun", "탑, 타워"),
    ("place", "noun", "장소, 곳, 두다"),

    # 401-450 (교통 / 이동 / 자연 / 날씨)
    ("car", "noun", "자동차, 차"),
    ("bus", "noun", "버스"),
    ("train", "noun", "기차, 열차, 훈련하다"),
    ("subway", "noun", "지하철"),
    ("taxi", "noun", "택시"),
    ("truck", "noun", "트럭"),
    ("airplane", "noun", "비행기"),
    ("plane", "noun", "비행기, 평면"),
    ("helicopter", "noun", "헬리콥터"),
    ("boat", "noun", "보트, 배"),
    ("ship", "noun", "배, 선박, 운송하다"),
    ("traffic", "noun", "교통, 교통량"),
    ("ticket", "noun", "표, 티켓"),
    ("seat", "noun", "좌석, 자리"),
    ("stop", "noun", "정류장, 멈추다"),
    ("gas", "noun", "가스, 휘발유"),
    ("wheel", "noun", "바퀴, 핸들"),
    ("nature", "noun", "자연, 본성"),
    ("sky", "noun", "하늘"),
    ("sun", "noun", "태양, 해"),
    ("moon", "noun", "달"),
    ("star", "noun", "별, 인기인"),
    ("cloud", "noun", "구름"),
    ("rain", "noun", "비, 비가 오다"),
    ("snow", "noun", "눈, 눈이 내리다"),
    ("wind", "noun", "바람"),
    ("fog", "noun", "안개"),
    ("storm", "noun", "폭풍, 폭풍우"),
    ("thunder", "noun", "천둥"),
    ("lightning", "noun", "번개"),
    ("rainbow", "noun", "무지개"),
    ("air", "noun", "공기, 대기"),
    ("earth", "noun", "지구, 땅, 흙"),
    ("land", "noun", "땅, 육지, 착륙하다"),
    ("ground", "noun", "지면, 바닥, 운동장"),
    ("sand", "noun", "모래"),
    ("dust", "noun", "먼지, 털다"),
    ("mud", "noun", "진흙"),
    ("rock", "noun", "바위, 암석, 흔들다"),
    ("stone", "noun", "돌, 보석"),
    ("mountain", "noun", "산"),
    ("hill", "noun", "언덕"),
    ("river", "noun", "강"),
    ("lake", "noun", "호수"),
    ("sea", "noun", "바다"),
    ("ocean", "noun", "대양, 바다"),
    ("beach", "noun", "해변, 바닷가"),
    ("coast", "noun", "해안, 연안"),
    ("island", "noun", "섬"),
    ("forest", "noun", "숲, 삼림"),

    # 451-500 (자연 / 식물 / 동물)
    ("wood", "noun", "나무, 목재, 숲"),
    ("tree", "noun", "나무"),
    ("plant", "noun", "식물, 공장, 심다"),
    ("flower", "noun", "꽃, 꽃이 피다"),
    ("rose", "noun", "장미"),
    ("leaf", "noun", "나뭇잎, 잎"),
    ("leaves", "noun", "나뭇잎들(복수)"),
    ("grass", "noun", "풀, 잔디"),
    ("seed", "noun", "씨앗, 종자"),
    ("branch", "noun", "나뭇가지, 지점"),
    ("root", "noun", "뿌리, 근원"),
    ("animal", "noun", "동물"),
    ("pet", "noun", "애완동물"),
    ("dog", "noun", "개"),
    ("puppy", "noun", "강아지"),
    ("cat", "noun", "고양이"),
    ("kitten", "noun", "새끼 고양이"),
    ("bird", "noun", "새"),
    ("chicken", "noun", "닭, 닭고기"),
    ("duck", "noun", "오리"),
    ("goose", "noun", "거위"),
    ("horse", "noun", "말"),
    ("cow", "noun", "암소, 소"),
    ("pig", "noun", "돼지"),
    ("sheep", "noun", "양"),
    ("goat", "noun", "염소"),
    ("rabbit", "noun", "토끼"),
    ("mouse", "noun", "쥐, 마우스"),
    ("rat", "noun", "쥐"),
    ("monkey", "noun", "원숭이"),
    ("bear", "noun", "곰, 견디다"),
    ("lion", "noun", "사자"),
    ("tiger", "noun", "호랑이"),
    ("elephant", "noun", "코끼리"),
    ("giraffe", "noun", "기린"),
    ("zebra", "noun", "얼룩말"),
    ("kangaroo", "noun", "캥거루"),
    ("panda", "noun", "판다"),
    ("fox", "noun", "여우"),
    ("wolf", "noun", "늑대"),
    ("deer", "noun", "사슴"),
    ("snake", "noun", "뱀"),
    ("frog", "noun", "개구리"),
    ("turtle", "noun", "거북이"),
    ("fish", "noun", "물고기"),
    ("whale", "noun", "고래"),
    ("dolphin", "noun", "돌고래"),
    ("shark", "noun", "상어"),
    ("insect", "noun", "곤충, 벌레"),
    ("ant", "noun", "개미"),

    # 501-550 (동물 / 색상 / 형태 / 기본 형용사)
    ("bee", "noun", "벌"),
    ("butterfly", "noun", "나비"),
    ("spider", "noun", "거미"),
    ("fly", "noun", "파리, 날다"),
    ("mosquito", "noun", "모기"),
    ("tail", "noun", "꼬리"),
    ("wing", "noun", "날개"),
    ("color", "noun", "색, 색깔"),
    ("red", "adjective", "빨간색의, 빨강"),
    ("blue", "adjective", "파란색의, 파랑"),
    ("yellow", "adjective", "노란색의, 노랑"),
    ("green", "adjective", "초록색의, 초록"),
    ("black", "adjective", "검은색의, 검정"),
    ("white", "adjective", "흰색의, 하양"),
    ("brown", "adjective", "갈색의, 갈색"),
    ("gray", "adjective", "회색의, 회색"),
    ("orange", "adjective", "주황색의, 오렌지"),
    ("pink", "adjective", "분홍색의, 분홍"),
    ("purple", "adjective", "보라색의, 보라"),
    ("gold", "noun", "금, 금색"),
    ("silver", "noun", "은, 은색"),
    ("bright", "adjective", "밝은, 영리한"),
    ("dark", "adjective", "어두운, 캄캄한"),
    ("light", "noun", "빛, 가벼운, 밝은"),
    ("big", "adjective", "큰, 커다란"),
    ("large", "adjective", "넓은, 거대한"),
    ("small", "adjective", "작은, 적은"),
    ("little", "adjective", "어린, 작은, 조금"),
    ("tiny", "adjective", "아주 작은"),
    ("huge", "adjective", "거대한, 막대한"),
    ("long", "adjective", "긴, 오래"),
    ("short", "adjective", "짧은, 키 작은"),
    ("tall", "adjective", "키가 큰, 높은"),
    ("high", "adjective", "높은, 높게"),
    ("low", "adjective", "낮은, 낮게"),
    ("deep", "adjective", "깊은"),
    ("shallow", "adjective", "얕은"),
    ("wide", "adjective", "넓은"),
    ("narrow", "adjective", "좁은"),
    ("thick", "adjective", "두꺼운, 굵은"),
    ("thin", "adjective", "얇은, 마른"),
    ("fat", "adjective", "뚱뚱한, 살찐"),
    ("heavy", "adjective", "무거운"),
    ("hot", "adjective", "뜨거운, 더운, 매운"),
    ("warm", "adjective", "따뜻한"),
    ("cool", "adjective", "시원한, 멋진"),
    ("cold", "adjective", "차가운, 추운, 감기"),
    ("dry", "adjective", "마른, 건조한"),
    ("wet", "adjective", "젖은, 축축한"),
    ("clean", "adjective", "깨끗한, 청소하다"),

    # 551-600 (성질 / 상태 / 감정 형용사)
    ("dirty", "adjective", "더러운"),
    ("fresh", "adjective", "신선한, 새로운"),
    ("sweet", "adjective", "달콤한, 다정한"),
    ("bitter", "adjective", "쓴, 쓰라린"),
    ("sour", "adjective", "신, 시큼한"),
    ("salty", "adjective", "짠, 짭짤한"),
    ("delicious", "adjective", "맛있는"),
    ("hard", "adjective", "단단한, 어려운, 열심히"),
    ("soft", "adjective", "부드러운, 푹신한"),
    ("rough", "adjective", "거친, 대략의"),
    ("smooth", "adjective", "매끄러운, 부드러운"),
    ("sharp", "adjective", "날카로운, 급격한"),
    ("fast", "adjective", "빠른, 빨리"),
    ("quick", "adjective", "재빠른, 신속한"),
    ("slow", "adjective", "느린, 천천히"),
    ("early", "adjective", "이른, 일찍"),
    ("late", "adjective", "늦은, 늦게"),
    ("new", "adjective", "새로운, 새 것"),
    ("old", "adjective", "오래된, 늙은"),
    ("young", "adjective", "젊은, 어린"),
    ("good", "adjective", "좋은, 착한"),
    ("nice", "adjective", "좋은, 멋진, 친절한"),
    ("great", "adjective", "위대한, 훌륭한, 큰"),
    ("fine", "adjective", "괜찮은, 좋은, 벌금"),
    ("bad", "adjective", "나쁜, 서투른"),
    ("terrible", "adjective", "끔찍한, 형편없는"),
    ("beautiful", "adjective", "아름다운, 예쁜"),
    ("pretty", "adjective", "예쁜, 꽤, 상당히"),
    ("cute", "adjective", "귀여운"),
    ("handsome", "adjective", "잘생긴, 멋진"),
    ("ugly", "adjective", "못생긴, 흉한"),
    ("smart", "adjective", "똑똑한, 영리한"),
    ("clever", "adjective", "영리한, 기발한"),
    ("wise", "adjective", "지혜로운, 현명한"),
    ("foolish", "adjective", "어리석은, 바보 같은"),
    ("stupid", "adjective", "어리석은, 바보 같은"),
    ("kind", "adjective", "친절한, 종류"),
    ("gentle", "adjective", "온화한, 다정한"),
    ("brave", "adjective", "용감한"),
    ("strong", "adjective", "강한, 튼튼한"),
    ("weak", "adjective", "약한, 힘없는"),
    ("rich", "adjective", "부유한, 풍부한"),
    ("poor", "adjective", "가난한, 불쌍한"),
    ("busy", "adjective", "바쁜"),
    ("free", "adjective", "자유로운, 무료의, 한가한"),
    ("quiet", "adjective", "조용한, 차분한"),
    ("loud", "adjective", "소리가 큰, 시끄러운"),
    ("noisy", "adjective", "시끄러운"),
    ("safe", "adjective", "안전한, 금고"),
    ("dangerous", "adjective", "위험한"),

    # 601-650 (감정 / 상태 / 진위 형용사)
    ("happy", "adjective", "행복한, 기쁜"),
    ("glad", "adjective", "기쁜, 반가운"),
    ("sad", "adjective", "슬픈"),
    ("angry", "adjective", "화난, 성난"),
    ("afraid", "adjective", "두려워하는, 무서워하는"),
    ("scared", "adjective", "겁먹은, 무서워하는"),
    ("tired", "adjective", "피곤한, 지친"),
    ("hungry", "adjective", "배고픈"),
    ("thirsty", "adjective", "목마른"),
    ("surprised", "adjective", "놀란"),
    ("lonely", "adjective", "외로운, 쓸쓸한"),
    ("proud", "adjective", "자랑스러운, 오만한"),
    ("shy", "adjective", "부끄러워하는, 수줍은"),
    ("nervous", "adjective", "긴장한, 불안한"),
    ("calm", "adjective", "침착한, 차분한"),
    ("easy", "adjective", "쉬운, 편안한"),
    ("difficult", "adjective", "어려운, 힘든"),
    ("simple", "adjective", "단순한, 간단한"),
    ("true", "adjective", "진실한, 진짜의"),
    ("false", "adjective", "거짓의, 틀린"),
    ("right", "adjective", "옳은, 오른쪽의, 권리"),
    ("wrong", "adjective", "틀린, 잘못된"),
    ("real", "adjective", "진짜의, 실제의"),
    ("ready", "adjective", "준비된"),
    ("sure", "adjective", "확신하는, 확실한"),
    ("clear", "adjective", "명확한, 맑은"),
    ("famous", "adjective", "유명한"),
    ("popular", "adjective", "인기 있는, 대중적인"),
    ("special", "adjective", "특별한"),
    ("strange", "adjective", "이상한, 낯선"),
    ("different", "adjective", "다른, 차이가 나는"),
    ("important", "adjective", "중요한"),
    ("necessary", "adjective", "필요한, 필수의"),
    ("possible", "adjective", "가능한"),
    ("impossible", "adjective", "불가능한"),
    ("lucky", "adjective", "운이 좋은, 다행인"),
    ("funny", "adjective", "재미있는, 웃긴"),
    ("interesting", "adjective", "흥미로운, 재미있는"),
    ("boring", "adjective", "지루한, 따분한"),
    ("careful", "adjective", "조심스러운, 주의 깊은"),
    ("careless", "adjective", "부주의한, 경솔한"),
    ("honest", "adjective", "정직한, 솔직한"),
    ("polite", "adjective", "예의 바른, 공손한"),
    ("useful", "adjective", "유용한, 쓸모 있는"),
    ("useless", "adjective", "쓸모없는"),
    ("perfect", "adjective", "완벽한"),
    ("whole", "adjective", "전체의, 온전한"),
    ("half", "noun", "절반, 반"),
    ("piece", "noun", "조각, 하나"),
    ("part", "noun", "부분, 일부, 부품"),

    # 651-700 (기본 동작 동사 1)
    ("be", "verb", "이다, 있다, 존재하다"),
    ("have", "verb", "가지고 있다, 먹다"),
    ("do", "verb", "하다, 행하다"),
    ("say", "verb", "말하다, 이야기하다"),
    ("go", "verb", "가다, 진행되다"),
    ("come", "verb", "오다, 도착하다"),
    ("see", "verb", "보다, 알다, 만나다"),
    ("look", "verb", "보다, 바라보다, ~처럼 보이다"),
    ("watch", "verb", "지켜보다, 시청하다, 시계"),
    ("hear", "verb", "듣다, 소리가 들리다"),
    ("listen", "verb", "귀 기울여 듣다, 경청하다"),
    ("feel", "verb", "느끼다, 기분이 들다"),
    ("smell", "verb", "냄새가 나다, 냄새를 맡다"),
    ("taste", "verb", "맛이 나다, 맛보다"),
    ("touch", "verb", "만지다, 감동시키다"),
    ("make", "verb", "만들다, ~하게 하다"),
    ("get", "verb", "얻다, 받다, 되다"),
    ("take", "verb", "가져가다, 데려가다, 타다"),
    ("give", "verb", "주다, 건네다"),
    ("bring", "verb", "가져오다, 데려오다"),
    ("carry", "verb", "나르다, 지니다"),
    ("send", "verb", "보내다, 발송하다"),
    ("receive", "verb", "받다, 수령하다"),
    ("put", "verb", "놓다, 두다"),
    ("keep", "verb", "유지하다, 보관하다"),
    ("hold", "verb", "잡고 있다, 개최하다"),
    ("catch", "verb", "잡다, 따라잡다, 병에 걸리다"),
    ("drop", "verb", "떨어뜨리다, 방울"),
    ("fall", "verb", "떨어지다, 넘어지다, 가을"),
    ("pick", "verb", "고르다, 뽑다, 꺾다"),
    ("pull", "verb", "당기다, 끌다"),
    ("push", "verb", "밀다, 누르다"),
    ("throw", "verb", "던지다"),
    ("hit", "verb", "치다, 때리다, 맞히다"),
    ("cut", "verb", "자르다, 베다"),
    ("break", "verb", "깨뜨리다, 부수다, 휴식"),
    ("open", "verb", "열다, 개장하다, 열린"),
    ("close", "verb", "닫다, 끝나다, 가까운"),
    ("shut", "verb", "닫다, 잠그다"),
    ("lock", "verb", "자물쇠로 잠그다, 자물쇠"),
    ("turn", "verb", "돌다, 돌리다, 차례"),
    ("move", "verb", "움직이다, 이사하다"),
    ("stop", "verb", "멈추다, 그만두다"),
    ("start", "verb", "시작하다, 출발하다"),
    ("begin", "verb", "시작하다"),
    ("finish", "verb", "끝내다, 마치다"),
    ("end", "verb", "끝나다, 끝"),
    ("stay", "verb", "머무르다, 유지하다"),
    ("wait", "verb", "기다리다"),
    ("leave", "verb", "떠나다, 남기다, 휴가"),

    # 701-750 (기본 동작 동사 2)
    ("arrive", "verb", "도착하다"),
    ("enter", "verb", "들어가다, 입학하다"),
    ("pass", "verb", "지나가다, 통과하다, 건네다"),
    ("cross", "verb", "건너다, 가로지르다, 십자가"),
    ("follow", "verb", "따라가다, 따르다"),
    ("lead", "verb", "이끌다, 안내하다"),
    ("run", "verb", "달리다, 운영하다"),
    ("walk", "verb", "걷다, 산책하다"),
    ("jump", "verb", "뛰다, 도약하다"),
    ("fly", "verb", "날다, 비행하다"),
    ("swim", "verb", "수영하다"),
    ("climb", "verb", "오르다, 등반하다"),
    ("ride", "verb", "타다, 승차"),
    ("drive", "verb", "운전하다, 몰다"),
    ("stand", "verb", "서다, 참다"),
    ("sit", "verb", "앉다"),
    ("lie", "verb", "눕다, 거짓말하다, 거짓말"),
    ("sleep", "verb", "자다, 잠"),
    ("wake", "verb", "깨어나다, 깨우다"),
    ("eat", "verb", "먹다"),
    ("drink", "verb", "마시다, 음료"),
    ("cook", "verb", "요리하다, 요리사"),
    ("bake", "verb", "굽다"),
    ("wash", "verb", "씻다, 세탁하다"),
    ("clean", "verb", "청소하다, 깨끗한"),
    ("wear", "verb", "입다, 착용하다"),
    ("dress", "verb", "옷을 입다, 드레스"),
    ("speak", "verb", "말하다, 연설하다"),
    ("talk", "verb", "이야기하다, 대화하다"),
    ("tell", "verb", "말해주다, 알리다"),
    ("ask", "verb", "묻다, 요청하다"),
    ("answer", "verb", "대답하다, 답"),
    ("call", "verb", "부르다, 전화하다"),
    ("shout", "verb", "소리치다, 외치다"),
    ("cry", "verb", "울다, 외치다"),
    ("laugh", "verb", "웃다, 비웃다"),
    ("smile", "verb", "미소 짓다, 미소"),
    ("think", "verb", "생각하다"),
    ("know", "verb", "알다, 알고 있다"),
    ("understand", "verb", "이해하다, 알아듣다"),
    ("learn", "verb", "배우다, 학습하다"),
    ("remember", "verb", "기억하다, 기억해내다"),
    ("forget", "verb", "잊다, 잊어버리다"),
    ("believe", "verb", "믿다, 생각하다"),
    ("hope", "verb", "바라다, 희망하다, 희망"),
    ("wish", "verb", "소원하다, 바라다, 소원"),
    ("want", "verb", "원하다, 바라다"),
    ("need", "verb", "필요로 하다, 필요"),
    ("like", "verb", "좋아하다, ~처럼"),
    ("love", "verb", "사랑하다, 사랑"),

    # 751-800 (기본 동작 동사 3 / 상호작용)
    ("hate", "verb", "싫어하다, 증오하다"),
    ("enjoy", "verb", "즐기다, 누리다"),
    ("prefer", "verb", "더 좋아하다, 선호하다"),
    ("help", "verb", "돕다, 도움"),
    ("save", "verb", "구하다, 절약하다, 저장하다"),
    ("use", "verb", "사용하다, 쓰다"),
    ("find", "verb", "찾다, 발견하다"),
    ("lose", "verb", "잃다, 지다, 패하다"),
    ("win", "verb", "이기다, 얻다"),
    ("buy", "verb", "사다, 구입하다"),
    ("sell", "verb", "팔다, 판매하다"),
    ("pay", "verb", "지불하다, 돈을 내다"),
    ("cost", "verb", "비용이 들다, 비용"),
    ("spend", "verb", "쓰다, 시간을 보내다"),
    ("work", "verb", "일하다, 작동하다, 일"),
    ("try", "verb", "노력하다, 시도하다"),
    ("change", "verb", "바꾸다, 변하다, 거스름돈"),
    ("grow", "verb", "자라다, 키우다, 재배하다"),
    ("live", "verb", "살다, 살아있는"),
    ("die", "verb", "죽다, 사망하다"),
    ("kill", "verb", "죽이다"),
    ("fight", "verb", "싸우다, 다투다, 싸움"),
    ("meet", "verb", "만나다, 충족시키다"),
    ("join", "verb", "함께하다, 가입하다"),
    ("invite", "verb", "초대하다, 부르다"),
    ("visit", "verb", "방문하다, 찾아가다"),
    ("welcome", "verb", "환영하다, 환영받는"),
    ("thank", "verb", "감사하다, 고마워하다"),
    ("excuse", "verb", "용서하다, 변명"),
    ("sorry", "adjective", "미안한, 유감스러운"),
    ("please", "adverb", "제발, 부디, 기쁘게 하다"),
    ("agree", "verb", "동의하다, 찬성하다"),
    ("refuse", "verb", "거절하다, 거부하다"),
    ("allow", "verb", "허용하다, 허락하다"),
    ("choose", "verb", "선택하다, 고르다"),
    ("decide", "verb", "결정하다, 결심하다"),
    ("plan", "verb", "계획하다, 계획"),
    ("prepare", "verb", "준비하다, 대비하다"),
    ("show", "verb", "보여주다, 나타나다, 쇼"),
    ("hide", "verb", "숨기다, 숨다"),
    ("cover", "verb", "덮다, 가리다, 표지"),
    ("fill", "verb", "채우다, 가득 차다"),
    ("empty", "adjective", "비어있는, 비우다"),
    ("share", "verb", "공유하다, 나누다, 몫"),
    ("lend", "verb", "빌려주다"),
    ("borrow", "verb", "빌리다"),
    ("return", "verb", "돌아가다, 반납하다, 귀환"),
    ("fix", "verb", "고치다, 수리하다, 고정하다"),
    ("build", "verb", "짓다, 건설하다"),
    ("paint", "verb", "칠하다, 페인트"),

    # 801-850 (부사 / 양 / 빈도 / 위치 부사)
    ("now", "adverb", "지금, 이제"),
    ("then", "adverb", "그때, 그리고 나서"),
    ("soon", "adverb", "곧, 머지않아"),
    ("already", "adverb", "이미, 벌써"),
    ("still", "adverb", "아직도, 여전히, 가만히 있는"),
    ("yet", "adverb", "아직, 벌써, 하지만"),
    ("again", "adverb", "다시, 또"),
    ("once", "adverb", "한 번, 예전에"),
    ("twice", "adverb", "두 번"),
    ("always", "adverb", "항상, 언제나"),
    ("usually", "adverb", "보통, 대개"),
    ("often", "adverb", "자주, 종종"),
    ("sometimes", "adverb", "때때로, 가끔"),
    ("seldom", "adverb", "거의 ~않는"),
    ("never", "adverb", "결코 ~않다"),
    ("ever", "adverb", "언젠가, 이제까지"),
    ("here", "adverb", "여기에, 이곳"),
    ("there", "adverb", "거기에, 저곳"),
    ("near", "adverb", "가까이, 가까운"),
    ("far", "adverb", "멀리, 먼"),
    ("away", "adverb", "떨어져, 멀리"),
    ("back", "adverb", "뒤로, 다시"),
    ("up", "adverb", "위로, 위에"),
    ("down", "adverb", "아래로, 아래에"),
    ("in", "adverb", "안에, 안으로"),
    ("out", "adverb", "밖에, 밖으로"),
    ("inside", "adverb", "안쪽에, 내부"),
    ("outside", "adverb", "바깥에, 외부"),
    ("front", "noun", "앞, 앞쪽"),
    ("side", "noun", "옆, 측면, 편"),
    ("top", "noun", "꼭대기, 맨 위, 최고의"),
    ("bottom", "noun", "바닥, 맨 아래"),
    ("center", "noun", "중심, 중앙, 센터"),
    ("middle", "noun", "가운데, 중간"),
    ("left", "adjective", "왼쪽의, 왼쪽, 남겨진"),
    ("right", "adjective", "오른쪽의, 오른쪽, 옳은"),
    ("north", "noun", "북쪽, 북부"),
    ("south", "noun", "남쪽, 남부"),
    ("east", "noun", "동쪽, 동부"),
    ("west", "noun", "서쪽, 서부"),
    ("very", "adverb", "매우, 아주"),
    ("too", "adverb", "너무, 또한, 역시"),
    ("quite", "adverb", "꽤, 상당히"),
    ("almost", "adverb", "거의"),
    ("enough", "adverb", "충분히, 충분한"),
    ("together", "adverb", "함께, 같이"),
    ("alone", "adverb", "혼자서, 외로이"),
    ("only", "adverb", "오직, 유일한"),
    ("just", "adverb", "방금, 그저, 공정한"),
    ("even", "adverb", "심지어, ~조차도, 평평한"),

    # 851-900 (일상 개념 / 사회 / 소통)
    ("name", "noun", "이름, 지명하다"),
    ("age", "noun", "나이, 연령, 시대"),
    ("birthday", "noun", "생일"),
    ("party", "noun", "파티, 정당"),
    ("gift", "noun", "선물, 재능"),
    ("present", "noun", "선물, 현재, 출석한, 제시하다"),
    ("holiday", "noun", "휴일, 공휴일, 휴가"),
    ("vacation", "noun", "휴가, 방학"),
    ("trip", "noun", "여행, 발을 헛디딤"),
    ("tour", "noun", "여행, 견학, 관광하다"),
    ("picnic", "noun", "소풍"),
    ("camp", "noun", "캠프, 야영지"),
    ("money", "noun", "돈, 화폐"),
    ("dollar", "noun", "달러"),
    ("cent", "noun", "센트"),
    ("won", "noun", "원(한국 화폐)"),
    ("price", "noun", "가격, 대가"),
    ("life", "noun", "삶, 생명, 인생"),
    ("death", "noun", "죽음, 사망"),
    ("dream", "noun", "꿈, 꿈꾸다"),
    ("hope", "noun", "희망, 바라다"),
    ("wish", "noun", "소원, 바라다"),
    ("luck", "noun", "행운, 운"),
    ("peace", "noun", "평화, 고요"),
    ("war", "noun", "전쟁, 전투"),
    ("news", "noun", "뉴스, 소식"),
    ("newspaper", "noun", "신문"),
    ("magazine", "noun", "잡지"),
    ("letter", "noun", "편지, 글자"),
    ("mail", "noun", "우편, 메일"),
    ("email", "noun", "이메일, 전자우편"),
    ("message", "noun", "메시지, 전갈"),
    ("post", "noun", "우편, 게시물, 기둥"),
    ("stamp", "noun", "우표, 도장"),
    ("picture", "noun", "그림, 사진"),
    ("photo", "noun", "사진"),
    ("sound", "noun", "소리, 건전한, ~하게 들리다"),
    ("noise", "noun", "소음, 잡음"),
    ("light", "noun", "빛, 가벼운"),
    ("shadow", "noun", "그림자"),
    ("line", "noun", "선, 줄, 늘어서다"),
    ("point", "noun", "점, 요점, 가리키다"),
    ("circle", "noun", "원, 동그라미"),
    ("square", "noun", "정사각형, 광장"),
    ("size", "noun", "크기, 치수"),
    ("shape", "noun", "모양, 형태"),
    ("weight", "noun", "무게, 체중"),
    ("speed", "noun", "속도, 빠르기"),
    ("way", "noun", "길, 방식"),
    ("step", "noun", "걸음, 계단, 조치"),

    # 901-950 (활동 / 상태 / 일반 개념)
    ("habit", "noun", "습관, 버릇"),
    ("rule", "noun", "규칙, 지배하다"),
    ("order", "noun", "주문, 순서, 명령하다"),
    ("custom", "noun", "관습, 풍습"),
    ("skill", "noun", "기술, 솜씨"),
    ("job", "noun", "직업, 일"),
    ("work", "noun", "일, 직장, 작품"),
    ("worker", "noun", "근로자, 일꾼"),
    ("boss", "noun", "상사, 두목"),
    ("king", "noun", "왕, 국왕"),
    ("queen", "noun", "여왕, 왕비"),
    ("prince", "noun", "왕자"),
    ("princess", "noun", "공주"),
    ("hero", "noun", "영웅, 주인공"),
    ("police", "noun", "경찰"),
    ("firefighter", "noun", "소방관"),
    ("pilot", "noun", "비행사, 조종사"),
    ("driver", "noun", "운전기사, 운전자"),
    ("cook", "noun", "요리사, 요리하다"),
    ("farmer", "noun", "농부"),
    ("singer", "noun", "가수"),
    ("dancer", "noun", "댄서, 무용수"),
    ("actor", "noun", "배우"),
    ("actress", "noun", "여배우"),
    ("artist", "noun", "화가, 예술가"),
    ("writer", "noun", "작가, 글쓴이"),
    ("scientist", "noun", "과학자"),
    ("magic", "noun", "마술, 마법"),
    ("accident", "noun", "사고, 재난"),
    ("trouble", "noun", "문제, 곤란, 괴롭히다"),
    ("danger", "noun", "위험"),
    ("safety", "noun", "안전"),
    ("fire", "noun", "불, 화재, 발사하다"),
    ("smoke", "noun", "연기, 담배를 피우다"),
    ("energy", "noun", "에너지, 활기"),
    ("power", "noun", "힘, 전력, 권력"),
    ("force", "noun", "힘, 강요하다"),
    ("gas", "noun", "가스, 기체"),
    ("oil", "noun", "기름, 석유"),
    ("gold", "noun", "금"),
    ("iron", "noun", "철, 다리미"),
    ("silver", "noun", "은"),
    ("plastic", "noun", "플라스틱"),
    ("glass", "noun", "유리, 안경"),
    ("wood", "noun", "나무, 목재"),
    ("paper", "noun", "종이"),
    ("box", "noun", "상자, 박스"),
    ("can", "noun", "캔, 통조림, ~할 수 있다"),
    ("rope", "noun", "밧줄, 로프"),
    ("string", "noun", "끈, 줄"),

    # 951-1000 (기초 마무리 / 감탄사 / 일상 부사)
    ("bell", "noun", "종, 벨"),
    ("flag", "noun", "깃발, 국기"),
    ("sign", "noun", "표지판, 신호, 서명하다"),
    ("mark", "noun", "자국, 표시, 채점하다"),
    ("cross", "noun", "십자가, 건너다"),
    ("hole", "noun", "구멍, 구덩이"),
    ("pocket", "noun", "주머니"),
    ("corner", "noun", "모퉁이, 구석"),
    ("end", "noun", "끝, 결말, 끝나다"),
    ("start", "noun", "시작, 출발"),
    ("side", "noun", "옆, 측면"),
    ("edge", "noun", "가장자리, 모서리"),
    ("space", "noun", "우주, 공간"),
    ("sky", "noun", "하늘"),
    ("ground", "noun", "땅, 지면"),
    ("grass", "noun", "풀, 잔디"),
    ("leaf", "noun", "잎사귀"),
    ("branch", "noun", "나뭇가지"),
    ("root", "noun", "뿌리"),
    ("bark", "noun", "나무껍질, 짖다"),
    ("yes", "interjection", "네, 예"),
    ("no", "interjection", "아니오, 없는"),
    ("not", "adverb", "~이 아니다"),
    ("oh", "interjection", "오, 아"),
    ("ah", "interjection", "아"),
    ("wow", "interjection", "와, 대단해"),
    ("hi", "interjection", "안녕"),
    ("hello", "interjection", "안녕하세요"),
    ("bye", "interjection", "안녕, 잘 가"),
    ("goodbye", "interjection", "작별 인사"),
    ("okay", "adjective", "괜찮은, 알았어"),
    ("well", "adverb", "잘, 좋게, 우물"),
    ("maybe", "adverb", "아마도, 어쩌면"),
    ("perhaps", "adverb", "아마, 혹시"),
    ("really", "adverb", "정말로, 참으로"),
    ("surely", "adverb", "확실히, 틀림없이"),
    ("certainly", "adverb", "틀림없이, 물론"),
    ("probably", "adverb", "아마도"),
    ("especially", "adverb", "특히, 각별히"),
    ("finally", "adverb", "마침내, 드디어"),
    ("suddenly", "adverb", "갑자기, 별안간"),
    ("slowly", "adverb", "천천히, 느리게"),
    ("quickly", "adverb", "빨리, 신속히"),
    ("easily", "adverb", "쉽게, 용이하게"),
    ("hardly", "adverb", "거의 ~않다"),
    ("nearly", "adverb", "거의"),
    ("clearly", "adverb", "분명하게, 또렷하게"),
    ("quietly", "adverb", "조용히"),
    ("loudly", "adverb", "시끄럽게, 크게"),
    ("happily", "adverb", "행복하게, 기쁘게"),
]


def generate_example(word: str, pos: str, meaning: str) -> tuple[str, str]:
    """단어별 자연스러운 예문 및 한국어 해석 생성"""
    if pos == "noun":
        return f"I need a {word}.", f"나는 {meaning}(이)가 필요하다."
    elif pos == "verb":
        return f"We should {word} today.", f"우리는 오늘 {meaning}해야 한다."
    elif pos == "adjective":
        return f"This looks very {word}.", f"이것은 매우 {meaning} 보여요."
    elif pos == "adverb":
        return f"She spoke {word}.", f"그녀는 {meaning} 말했다."
    elif pos == "number":
        return f"There are {word} items on the desk.", f"책상 위에 {meaning}개의 물건이 있다."
    elif pos == "pronoun":
        return f"{word.capitalize()} is very important to us.", f"{meaning}은 우리에게 매우 중요하다."
    elif pos == "preposition":
        return f"The book is {word} the table.", f"그 책은 탁자 {meaning}에 있다."
    else:
        return f"This is an example for {word}.", f"이것은 {word}의 예문입니다."


def build_level_1_full() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    print("==================================================")
    print(" Level 1 기초 1,000단어 데이터셋 구축 시작")
    print("==================================================")

    entries: list[dict[str, Any]] = []
    raw_lines: list[str] = []

    # 1,000개 단어 생성
    total = len(RAW_WORDS_1000)
    print(f"총 단어 수: {total}개")

    for idx, (word, pos, meaning) in enumerate(RAW_WORDS_1000, start=1):
        ex_en, ex_ko = generate_example(word, pos, meaning)
        word_id = f"L1-{idx:04d}"

        entry = {
            "id": word_id,
            "word": word,
            "level": 1,
            "pos": pos,
            "meaning": meaning,
            "phonetics": {
                "us": f"/{word}/",
                "uk": f"/{word}/",
            },
            "audio": {
                "us": f"https://api.dictionaryapi.dev/media/pronunciations/en/{word.lower()}-us.mp3",
                "uk": f"https://api.dictionaryapi.dev/media/pronunciations/en/{word.lower()}-uk.mp3",
            },
            "example_en": ex_en,
            "example_ko": ex_ko,
            "synonyms": [],
            "antonyms": [],
        }
        entries.append(entry)
        raw_lines.append(f"{word},{meaning}")

    # level_1.json 저장
    output_file = DATA_DIR / "level_1.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)

    # raw/level_1_words.txt 동기화 저장
    raw_file = RAW_DIR / "level_1_words.txt"
    with open(raw_file, "w", encoding="utf-8") as f:
        f.write("\n".join(raw_lines) + "\n")

    # SHA-256 계산
    hasher = hashlib.sha256()
    with open(output_file, "rb") as f:
        while chunk := f.read(8192):
            hasher.update(chunk)
    sha256 = hasher.hexdigest()

    # manifest.json 갱신
    manifest_path = DATA_DIR / "manifest.json"
    manifest_data: dict[str, Any] = {"version": "1.0.0", "updated_at": datetime.now(timezone.utc).isoformat(), "levels": {}}

    if manifest_path.exists():
        try:
            with open(manifest_path, "r", encoding="utf-8") as f:
                manifest_data = json.load(f)
        except Exception:
            pass

    manifest_data.setdefault("levels", {})["1"] = {
        "name": "기초",
        "count": len(entries),
        "file": "level_1.json",
        "sha256": sha256,
    }

    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest_data, f, ensure_ascii=False, indent=2)

    print(f"\n-> level_1.json 생성 완료: 정확히 {len(entries)}단어")
    print(f"-> level_1_words.txt 동기화 완료: {len(raw_lines)}단어")
    print(f"-> manifest.json Level 1 카운트(1000) 갱신 완료!")
    print("==================================================")


if __name__ == "__main__":
    build_level_1_full()
