# -*- coding: utf-8 -*-
"""
Level 1 정통 맞춤형 예문 데이터 Part 2 (단어 201 ~ 400)
초등/기초(A1~A2) 수준의 자연스러운 일상 회화 문장 및 매끄러운 한국어 번역
"""

PART2_SENTENCES = {
    # 201-220 (채소 / 식사 / 식기)
    201: ("Eating green vegetables is very good for your health.", "녹색 채소를 먹는 것은 건강에 아주 좋다."),
    202: ("The red tomato is fresh and juicy.", "빨간 토마토가 신선하고 과즙이 풍부하다."),
    203: ("We made mashed potatoes with warm milk and butter.", "우리는 따뜻한 우유와 버터로 으깬 감자를 만들었다."),
    204: ("Rabbits like to munch on crunchy orange carrots.", "토끼는 아삭아삭한 주황색 당근을 베어 먹는 것을 좋아한다."),
    205: ("Chopping an onion often makes your eyes water.", "양파를 썰면 눈물이 자주 난다."),
    206: ("The family gathered around the table for a warm evening meal.", "가족들이 따뜻한 저녁 식사를 위해 식탁에 둘러앉았다."),
    207: ("What did you eat for breakfast this morning?", "오늘 아침 식사로 무엇을 드셨나요?"),
    208: ("Let's have a sandwich together for lunch.", "점심으로 샌드위치를 함께 먹자."),
    209: ("We reserved a table for dinner at six o'clock.", "우리는 6시에 저녁 식사를 위해 테이블을 예약했다."),
    210: ("This Italian restaurant serves great pasta and pizza.", "이 이탈리아 식당은 훌륭한 파스타와 피자를 제공한다."),
    211: ("We enjoyed iced tea at a cozy cafe down the street.", "우리는 골목길 아늑한 카페에서 아이스티를 즐겼다."),
    212: ("The waiter handed us the dinner menu.", "웨이터가 우리에게 저녁 메뉴판을 건네주었다."),
    213: ("May I have another cup of warm water?", "따뜻한 물 한 컵 더 주시겠어요?"),
    214: ("Be careful not to drop that fragile glass.", "깨지기 쉬운 유리잔을 떨어뜨리지 않도록 조심해."),
    215: ("She arranged colorful fruit on a white plate.", "그녀는 흰 접시 위에 알록달록한 과일을 가지런히 담았다."),
    216: ("This spicy noodle dish is very popular in Korea.", "이 매콤한 면 요리는 한국에서 매우 인기가 많다."),
    217: ("He ate a warm bowl of chicken soup.", "그는 따뜻한 닭고기 수프 한 그릇을 먹었다."),
    218: ("Use a spoon to eat the hot vegetable soup.", "뜨거운 야채수프를 먹을 때는 숟가락을 사용하세요."),
    219: ("He picked up a piece of melon with his fork.", "그는 포크로 멜론 한 조각을 집었다."),
    220: ("Please handle the sharp kitchen knife with care.", "날카로운 주방 칼은 조심해서 다루세요."),

    # 221-240 (용기 / 집 / 구조 / 방)
    221: ("She carried a reusable water bottle in her backpack.", "그녀는 배낭에 다회용 물병을 넣고 다녔다."),
    222: ("They live in a beautiful house with a red roof.", "그들은 빨간 지붕이 있는 예쁜 집에 산다."),
    223: ("There is no place like home after a long journey.", "긴 여행을 마치고 나면 집만 한 곳이 없다."),
    224: ("Our modern apartment is close to the subway station.", "우리 아파트는 지하철역에서 가깝다."),
    225: ("Keep your room tidy and clean every day.", "네 방을 매일 깔끔하고 깨끗하게 정돈해라."),
    226: ("Please knock on the door before you enter.", "방에 들어가기 전에 문을 노크해 주세요."),
    227: ("Open the window to let some fresh air in.", "신선한 공기가 들어오도록 창문을 열어라."),
    228: ("We hung a colorful picture on the living room wall.", "우리는 거실 벽에 알록달록한 그림을 걸었다."),
    229: ("Please wipe the spilled water off the floor.", "바닥에 쏟은 물을 닦아 주세요."),
    230: ("Solar panels were installed on the house roof.", "주택 지붕 위에 태양광 패널이 설치되었다."),
    231: ("The lamp hung down from the high ceiling.", "램프가 높은 천장에서 아래로 매달려 있었다."),
    232: ("Mom is preparing a delicious lunch in the kitchen.", "엄마가 주방에서 맛있는 점심을 준비하고 계신다."),
    233: ("Wash your hands with soap in the bathroom.", "욕실에서 비누로 손을 깨끗이 씻으세요."),
    234: ("Her cozy bedroom has a wide window overlooking the trees.", "그녀의 아늑한 침실에는 나무들이 내려다보이는 넓은 창문이 있다."),
    235: ("The whole family watches television in the living room.", "온 가족이 거실에서 텔레비전을 본다."),
    236: ("We planted red roses and sunflowers in our garden.", "우리는 정원에 빨간 장미와 해바라기를 심었다."),
    237: ("The children are playing tag in the front yard.", "아이들이 앞마당에서 술래잡기를 하고 있다."),
    238: ("Remember to close the garden gate behind you.", "나갈 때 정원 문을 꼭 닫아 주세요."),
    239: ("A white wooden fence surrounds the lovely cottage.", "하얀 나무 울타리가 예쁜 오두막을 둘러싸고 있다."),
    240: ("I used the front door key to unlock the house.", "나는 현관문 열쇠를 사용해 집 문을 열었다."),

    # 241-260 (가구 / 가전 / 생활용품)
    241: ("Make your bed neatly after you wake up.", "일어난 후에는 이부자리를 단정하게 정리해라."),
    242: ("Let's put the dinner plates on the dining table.", "식탁 위에 저녁 식사용 접시들을 올려놓자."),
    243: ("Please pull up a chair and sit down with us.", "의자를 당겨서 우리와 함께 앉으세요."),
    244: ("He sat at his study desk to do his homework.", "그는 숙제를 하기 위해 책상 앞에 앉았다."),
    245: ("Grandfather fell asleep on the comfortable sofa.", "할아버지는 편안한 소파에서 잠이 드셨다."),
    246: ("Turn on the reading lamp when it gets dark.", "날이 어두워지면 독서용 스탠드를 켜라."),
    247: ("She looked at herself in the mirror before leaving.", "그녀는 외출하기 전에 거울에 자신을 비춰 보았다."),
    248: ("There are many picture books on the bookshelf.", "책꽂이에 많은 그림책이 꽂혀 있다."),
    249: ("Draw the curtains to keep the bright sunlight out.", "눈부신 햇빛을 가리기 위해 커튼을 쳐라."),
    250: ("Cover yourself with a warm blanket on cold nights.", "추운 밤에는 따뜻한 담요를 덮으세요."),
    251: ("This soft pillow helps me sleep comfortably.", "이 푹신한 베개 덕분에 편안하게 잠을 잘 잔다."),
    252: ("Dry your wet hands with a clean towel.", "깨끗한 수건으로 젖은 손을 닦으세요."),
    253: ("Wash your hands thoroughly with warm water and soap.", "따뜻한 물과 비누로 손을 깨끗하게 씻으세요."),
    254: ("Use a soft hairbrush to untangle your hair.", "부드러운 빗을 사용하여 엉킨 머리를 빗으세요."),
    255: ("Please throw the candy wrapper into the trash can.", "사탕 껍질은 쓰레기통에 버려 주세요."),
    256: ("The telephone rang while we were having lunch.", "우리가 점심을 먹고 있을 때 전화가 울렸다."),
    257: ("She answered her mobile phone right away.", "그녀는 휴대전화를 즉시 받았다."),
    258: ("We gathered to watch the soccer final on television.", "우리는 텔레비전으로 축구 결승전을 보기 위해 모였다."),
    259: ("My grandparents still listen to the morning news on the radio.", "우리 조부모님은 아직도 라디오로 아침 뉴스를 들으신다."),
    260: ("I turned on my laptop computer to do research.", "나는 자료 조사를 하기 위해 노트북 컴퓨터를 켰다."),

    # 261-280 (IT / 옷 / 신발)
    261: ("You can search for lots of information on the internet.", "인터넷에서 많은 정보를 검색할 수 있다."),
    262: ("He took a great family picture with his digital camera.", "그는 디지털카메라로 멋진 가족사진을 찍었다."),
    263: ("Fold your clean clothes and put them in the drawer.", "깨끗한 옷을 개어서 서랍에 넣으세요."),
    264: ("He wore a crisp white shirt to the interview.", "그는 면접에 깔끔한 흰색 셔츠를 입고 갔다."),
    265: ("I like wearing a comfortable cotton t-shirt in summer.", "나는 여름에 편안한 면 티셔츠를 입는 것을 좋아한다."),
    266: ("Hang your black pants neatly in the closet.", "검은색 바지를 옷장에 가지런히 걸어 두어라."),
    267: ("Blue jeans go well with almost any t-shirt.", "청바지는 거의 모든 티셔츠와 잘 어울린다."),
    268: ("She wore a pretty floral dress to the wedding.", "그녀는 결혼식에 예쁜 꽃무늬 원피스를 입고 갔다."),
    269: ("The school uniform includes a pleated navy skirt.", "학교 교복에는 주름진 남색 치마가 포함되어 있다."),
    270: ("The businessman wore a formal dark suit.", "그 사업가는 단정한 어두운색 정장을 입었다."),
    271: ("Put on your thick winter coat before going outside.", "밖에 나가기 전에 두꺼운 겨울 코트를 입어라."),
    272: ("Zip up your warm fleece jacket against the wind.", "바람을 막기 위해 따뜻한 플리스 재킷의 지퍼를 올려라."),
    273: ("Grandmother knitted a soft woolen sweater for me.", "할머니께서 나를 위해 부드러운 털 스웨터를 떠 주셨다."),
    274: ("He wore a wide-brimmed straw hat at the sunny beach.", "그는 햇볕이 내리쬐는 해변에서 챙이 넓은 밀짚모자를 썼다."),
    275: ("Put on your baseball cap before going to practice.", "연습하러 가기 전에 야구 모자를 써라."),
    276: ("Take off your shoes before entering the house.", "집에 들어가기 전에 신발을 벗으세요."),
    277: ("He tied the laces of his left running shoe.", "그는 왼쪽 러닝화의 끈을 묶었다."),
    278: ("Wear warm wool socks to keep your feet cozy.", "발을 따뜻하게 유지하려면 털양말을 신으세요."),
    279: ("Put on your rain boots on rainy days.", "비 오는 날에는 장화를 신어라."),
    280: ("Wear warm gloves to protect your hands from the snow.", "눈으로부터 손을 보호하기 위해 따뜻한 장갑을 끼세요."),

    # 281-300 (패션잡화 / 학교 / 수업)
    281: ("She wrapped a cozy red scarf around her neck.", "그녀는 목에 따뜻한 빨간 목도리를 둘렀다."),
    282: ("Fasten your seat belt securely in the car.", "차 안에서는 안전벨트를 꼭 매세요."),
    283: ("He adjusted his silk tie in front of the mirror.", "그는 거울 앞에서 실크 넥타이를 매만졌다."),
    284: ("He kept a coin purse safely in his jacket pocket.", "그는 재킷 주머니에 동전 지갑을 안전하게 넣어 두었다."),
    285: ("She fastened the top button of her coat.", "그녀는 코트의 맨 위 단추를 잠갔다."),
    286: ("Pull up the zipper on your jacket so you stay warm.", "따뜻하게 체온을 유지하려면 재킷 지퍼를 올려라."),
    287: ("Grandpa put on his reading glasses to read the paper.", "할아버지는 신문을 읽기 위해 돋보기안경을 쓰셨다."),
    288: ("Wear sunglasses to protect your eyes from the bright sunlight.", "눈부신 햇빛으로부터 눈을 보호하기 위해 선글라스를 쓰세요."),
    289: ("He checked his wrist watch to see what time it was.", "그는 몇 시인지 확인하기 위해 손목시계를 보았다."),
    290: ("She wears a shiny silver ring on her finger.", "그녀는 손가락에 반짝이는 은반지를 끼고 있다."),
    291: ("Don't forget to take an umbrella on rainy days.", "비 오는 날에는 우산 챙기는 것을 잊지 마라."),
    292: ("She carried a reusable canvas shopping bag.", "그녀는 재사용 가능한 장바구니 가방을 들고 다녔다."),
    293: ("He took some cash out of his leather wallet.", "그는 가죽 지갑에서 현금을 조금 꺼냈다."),
    294: ("Pack your textbooks neatly into your school backpack.", "교과서를 학교 책가방에 가지런히 챙겨라."),
    295: ("Our elementary school has a large green playground.", "우리 초등학교에는 넓은 초록색 운동장이 있다."),
    296: ("Every student listened attentively to the teacher.", "모든 학생이 선생님의 말씀에 귀를 기울였다."),
    297: ("Our homeroom teacher greeted us with a bright smile.", "담임선생님은 환한 미소로 우리를 맞이해 주셨다."),
    298: ("Our science class starts at nine o'clock in the morning.", "우리 과학 수업은 오전 9시에 시작된다."),
    299: ("The students walked quietly into the bright classroom.", "학생들은 밝은 교실 안으로 조용히 들어갔다."),
    300: ("Today's history lesson was very exciting.", "오늘의 역사 수업은 정말 흥미진진했다."),

    # 301-320 (학용품 / 시험 / 질문)
    301: ("Open your English book to page twenty-five.", "영어책 25쪽을 펴세요."),
    302: ("I wrote down the teacher's explanation in my notebook.", "나는 선생님의 설명을 공책에 적었다."),
    303: ("Fold a piece of white paper in half.", "하얀 종이 한 장을 반으로 접으세요."),
    304: ("Sign your name at the bottom with a blue pen.", "파란색 펜으로 맨 아래에 이름을 서명하세요."),
    305: ("Sharpen your pencil before the test starts.", "시험이 시작되기 전에 연필을 깎아 두어라."),
    306: ("Use an eraser to rub out the pencil mistake.", "연필로 쓴 실수를 지우개로 지우세요."),
    307: ("Draw a straight line across the page with a ruler.", "자를 대고 페이지에 직선을 그어라."),
    308: ("The child drew a colorful rainbow with crayons.", "아이는 크레파스로 알록달록한 무지개를 그렸다."),
    309: ("Be careful when cutting paper with sharp scissors.", "날카로운 가위로 종이를 자를 때는 조심하세요."),
    310: ("Use a glue stick to stick the picture onto the cardboard.", "풀을 사용해 도화지에 그림을 붙이세요."),
    311: ("The teacher wrote new vocabulary words on the board.", "선생님께서 칠판에 새로운 어휘 단어들을 적으셨다."),
    312: ("He picked up a piece of white chalk to draw.", "그는 그림을 그리기 위해 흰색 분필 한 조각을 집어 들었다."),
    313: ("Keep your study desk neat and organized.", "공부 책상을 깔끔하고 정돈된 상태로 유지해라."),
    314: ("We borrowed interesting mystery novels from the public library.", "우리는 공공도서관에서 재미있는 추리소설을 빌렸다."),
    315: ("Finish your math homework before going out to play.", "놀러 나가기 전에 수학 숙제를 끝마쳐라."),
    316: ("The final exam will cover everything we learned this semester.", "기말고사는 이번 학기에 배운 모든 범위를 다룬다."),
    317: ("We studied hard and passed our English vocabulary test.", "우리는 열심히 공부해 영어 단어 시험을 통과했다."),
    318: ("She worked hard and received an excellent grade in science.", "그녀는 열심히 노력하여 과학 과목에서 훌륭한 성적을 받았다."),
    319: ("The team achieved the highest score in the quiz competition.", "팀은 퀴즈 대회에서 최고 점수를 획득했다."),
    320: ("Raise your hand if you have a question.", "질문이 있으신 분은 손을 들어 주세요."),

    # 321-340 (언어 / 교과목 / 활동)
    321: ("He gave a clear and helpful answer to my question.", "그는 내 질문에 명확하고 유익한 대답을 주었다."),
    322: ("We worked together to solve the difficult math problem.", "우리는 어려운 수학 문제를 풀기 위해 함께 머리를 맞댔다."),
    323: ("Look up the unfamiliar word in the English dictionary.", "생소한 단어는 영어사전에서 찾아보아라."),
    324: ("Write a complete English sentence on your paper.", "종이 위에 온전한 영어 문장을 작성하세요."),
    325: ("Grandmother told us an exciting fairy tale story.", "할머니께서 우리에게 재미있는 동화 이야기를 들려주셨다."),
    326: ("Turn to page fifty in your textbook.", "교과서 50쪽을 펴세요."),
    327: ("She wrote a handwritten thank-you letter to her teacher.", "그녀는 선생님께 손으로 직접 쓴 감사 편지를 보냈다."),
    328: ("Write down your phone number on this paper.", "이 종이에 당신의 전화번호를 적어 주세요."),
    329: ("Science is my favorite subject in school.", "과학은 학교에서 내가 가장 좋아하는 과목이다."),
    330: ("We practiced multiplication during math class.", "우리는 수학 시간에 곱셈을 연습했다."),
    331: ("We did a fun experiment in the science lab.", "우리는 과학 실험실에서 재미있는 실험을 했다."),
    332: ("We learn about world civilizations in history class.", "우리는 역사 시간에 세계 문명에 대해 배운다."),
    333: ("She drew a lovely watercolor landscape in art class.", "그녀는 미술 시간에 멋진 수채화 풍경화를 그렸다."),
    334: ("Listening to classical music helps me relax and concentrate.", "클래식 음악을 들으면 마음이 편안해지고 집중이 잘된다."),
    335: ("Speaking English with friends helps you improve quickly.", "친구들과 영어로 대화하면 실력이 빠르게 늘어난다."),
    336: ("Korean traditional food is delicious and healthy.", "한국 전통 음식은 맛있고 건강에도 좋다."),
    337: ("We ran five laps inside the indoor school gym.", "우리는 실내 학교 체육관 안을 다섯 바퀴 뛰었다."),
    338: ("Children were laughing and playing on the playground swings.", "아이들이 운동장 그네에서 웃으며 즐겁게 놀고 있었다."),
    339: ("I study for one hour every evening after dinner.", "나는 저녁 식사 후 매일 저녁 한 시간씩 공부한다."),
    340: ("Children learn new things by asking curious questions.", "아이들은 호기심 어린 질문을 던지며 새로운 것을 배운다."),

    # 341-360 (동사 / 놀이 / 스포츠)
    341: ("He loves to teach young kids how to swim.", "그는 어린아이들에게 수영하는 법을 가르치는 것을 매우 좋아한다."),
    342: ("I like to read an adventure novel before going to sleep.", "나는 자기 전에 모험 소설 읽는 것을 좋아한다."),
    343: ("Please write down your name and email address clearly.", "당신의 이름과 이메일 주소를 또렷하게 적어 주세요."),
    344: ("Use your pencil to draw a picture of your house.", "연필로 네가 사는 집의 그림을 그려 보아라."),
    345: ("We helped paint the school fence with bright blue paint.", "우리는 학교 울타리를 밝은 파란색 페인트로 칠하는 것을 도왔다."),
    346: ("The school choir will sing a cheerful song together.", "학교 합창단이 함께 경쾌한 노래를 부를 것이다."),
    347: ("The children love to dance happily to energetic music.", "아이들은 신나는 음악에 맞춰 즐겁게 춤추는 것을 좋아한다."),
    348: ("Let's go outside and play badminton in the park.", "밖에 나가서 공원에서 배드민턴을 치며 놀자."),
    349: ("We played an exciting board game with our friends.", "우리는 친구들과 재미있는 보드게임을 했다."),
    350: ("The toddler shared his toy train with his little brother.", "아장아장 걷는 아기는 장난감 기차를 남동생과 나눠 갖고 놀았다."),
    351: ("She hugged her favorite teddy bear doll tightly.", "그녀는 가장 좋아하는 곰 인형을 꼭 껴안았다."),
    352: ("Kick the soccer ball into the goal net.", "축구공을 골대 안으로 힘껏 차라."),
    353: ("Regular sport activities keep you fit and strong.", "규칙적인 운동은 몸을 건강하고 튼튼하게 유지해 준다."),
    354: ("We played a thrilling soccer match yesterday afternoon.", "우리는 어제 오후에 흥미진진한 축구 경기를 했다."),
    355: ("He hit a home run in the local baseball championship.", "그는 지역 야구 선수권 대회에서 홈런을 쳤다."),
    356: ("She shot the basketball right into the hoop.", "그녀는 농구공을 림 안으로 정확하게 던져 넣었다."),
    357: ("We enjoyed a lively game of beach volleyball.", "우리는 해변에서 신나는 비치발리볼 경기를 즐겼다."),
    358: ("Let's play a friendly match of table tennis.", "우리 가볍게 탁구 친선 경기 한 판 하자."),
    359: ("Swimming in the cool pool is refreshing in hot summer.", "더운 여름에 시원한 수영장에서 수영하는 것은 정말 상쾌하다."),
    360: ("He goes running in the local park every morning.", "그는 매일 아침 동네 공원에서 달리기 운동을 한다."),

    # 361-380 (취미 / 문화 / 도시 / 도로)
    361: ("He rode his new mountain bike along the river trail.", "그는 강변 산책로를 따라 새 산악자전거를 탔다."),
    362: ("Riding a bicycle is an eco-friendly way to travel.", "자전거를 타는 것은 친환경적인 이동 방식이다."),
    363: ("Her favorite creative hobby is baking fruit cakes.", "그녀가 가장 좋아하는 창의적인 취미는 과일 케이크 굽기이다."),
    364: ("We watched an exciting animated movie at home.", "우리는 집에서 재미있는 애니메이션 영화를 보았다."),
    365: ("Let's go to the downtown cinema to see the latest film.", "최신 영화를 보러 시내 영화관에 가자."),
    366: ("We watched a wonderful musical performance at the theater.", "우리는 극장에서 멋진 뮤지컬 공연을 관람했다."),
    367: ("The national museum displays ancient historic treasures.", "국립 박물관에는 고대의 역사적 유물들이 전시되어 있다."),
    368: ("We saw lovely giraffes and playful monkeys at the zoo.", "우리는 동물원에서 사랑스러운 기린과 장난꾸러기 원숭이를 보았다."),
    369: ("Families enjoy walking together in the leafy public park.", "가족들이 나무가 우거진 공원에서 함께 산책하는 것을 즐긴다."),
    370: ("We sat on a wooden bench under a shady tree.", "우리는 그늘진 나무 아래 나무 벤치에 앉았다."),
    371: ("Seoul is a vibrant and bustling capital city.", "서울은 활기차고 분주한 수도 도시이다."),
    372: ("He grew up in a quiet and peaceful seaside town.", "그는 조용하고 평화로운 바닷가 마을에서 자랐다."),
    373: ("The traditional village preserves old customs and houses.", "그 전통 마을은 옛 풍습과 가옥들을 잘 보존하고 있다."),
    374: ("Korea is a beautiful country with four distinct seasons.", "한국은 사계절이 뚜렷한 아름다운 나라이다."),
    375: ("People from all over the world gathered for the festival.", "축제를 위해 전 세계 곳곳에서 사람들이 모였다."),
    376: ("Look both ways before crossing the busy street.", "번잡한 거리를 건너기 전에는 양쪽을 모두 살피세요."),
    377: ("The winding country road led through golden wheat fields.", "구불구불한 시골길은 황금빛 밀밭 사이로 이어졌다."),
    378: ("Could you please tell me the way to the subway station?", "지하철역으로 가는 길을 알려주시겠어요?"),
    379: ("The long suspension bridge crosses over the wide river.", "긴 현수교가 넓은 강 위를 가로지르고 있다."),
    380: ("The flower shop is located right on the street corner.", "꽃집은 길모퉁이 바로 그곳에 자리 잡고 있다."),

    # 381-400 (건물 / 공공기관 / 시설)
    381: ("The new modern office building has fifty floors.", "신축 현대식 사무실 건물은 50층 규모이다."),
    382: ("She bought a souvenir at the gift shop.", "그녀는 기념품 가게에서 기념품을 하나 샀다."),
    383: ("The grocery store sells fresh fruits and milk.", "그 식료품점은 신선한 과일과 우유를 판매한다."),
    384: ("Farmers sell fresh seasonal vegetables at the open market.", "농부들이 열린 시장에서 신선한 제철 채소를 판매한다."),
    385: ("We bought groceries for the week at the supermarket.", "우리는 일주일치 식료품을 슈퍼마켓에서 샀다."),
    386: ("She went to the bank to deposit her savings.", "그녀는 저축한 돈을 입금하러 은행에 갔다."),
    387: ("I dropped off a package at the neighborhood post office.", "나는 동네 우체국에 소포를 접수하러 갔다."),
    388: ("Call the police immediately in case of emergency.", "위급한 상황이 발생하면 즉시 경찰에 신고하세요."),
    389: ("The fire truck rushed out of the fire station.", "소방차가 소방서에서 긴급 출동했다."),
    390: ("We boarded the express train at the central station.", "우리는 중앙역에서 고속열차에 탑승했다."),
    391: ("We arrived at the international airport two hours early.", "우리는 국제공항에 두 시간 일찍 도착했다."),
    392: ("We stayed at a comfortable hotel near the beach.", "우리는 해변 근처의 안락한 호텔에 머물렀다."),
    393: ("Fresh organic milk and eggs come directly from the farm.", "신선한 유기농 우유와 달걀은 농장에서 직접 공수된다."),
    394: ("The car assembly factory employs hundreds of local workers.", "그 자동차 조립 공장은 수백 명의 지역 근로자를 고용하고 있다."),
    395: ("He works diligently at a software development office.", "그는 소프트웨어 개발 사무실에서 성실하게 일한다."),
    396: ("The church bells rang softly on Sunday morning.", "일요일 아침에 교회 종소리가 은은하게 울려 퍼졌다."),
    397: ("We visited an ancient Buddhist temple in the mountains.", "우리는 산속에 있는 유서 깊은 사찰을 방문했다."),
    398: ("The ancient stone castle stands on top of the hill.", "고대 석조 성곽이 언덕 꼭대기에 웅장하게 서 있다."),
    399: ("We rode an elevator to the observation deck of the tower.", "우리는 엘리베이터를 타고 탑의 전망대로 올라갔다."),
    400: ("This quiet park is a wonderful place to relax.", "이 조용한 공원은 휴식을 취하기에 참 멋진 장소이다."),
}
