# -*- coding: utf-8 -*-
"""
Level 1 정통 맞춤형 예문 데이터 Part 4 (단어 601 ~ 800)
초등/기초(A1~A2) 수준의 자연스러운 일상 회화 문장 및 매끄러운 한국어 번역
"""

PART4_SENTENCES = {
    # 601-620 (감정 / 상태 / 난이도)
    601: ("The children were very happy when school vacation started.", "방학이 시작되자 아이들은 몹시 행복해했다."),
    602: ("I am so glad to see you again after such a long time.", "오랜만에 너를 다시 보게 되어 정말 기쁘다."),
    603: ("She felt sad when her best friend moved to another city.", "가장 친한 친구가 다른 도시로 이사를 가자 그녀는 슬펐다."),
    604: ("He was angry because someone accidentally broke his toy.", "누군가 실수로 자신의 장난감을 망가뜨려서 그는 화가 났다."),
    605: ("Don't be afraid to make mistakes while learning English.", "영어를 배울 때 실수하는 것을 두려워하지 마라."),
    606: ("The sudden loud noise made the little puppy scared.", "갑작스러운 큰 소리에 작은 강아지가 깜짝 놀라 겁을 먹었다."),
    607: ("I feel very tired after walking all afternoon in the park.", "오후 내내 공원에서 걸었더니 몸이 무척 피곤하다."),
    608: ("I am so hungry that I could eat two sandwiches right now.", "지금 샌드위치를 두 개라도 먹을 수 있을 만큼 배가 고프다."),
    609: ("Drink plenty of cool water if you feel thirsty.", "목이 마르면 시원한 물을 충분히 마셔라."),
    610: ("She was pleasantly surprised by the unexpected birthday gift.", "그녀는 뜻밖의 생일 선물에 기분 좋게 깜짝 놀랐다."),
    611: ("The new student felt a bit lonely on his first day at school.", "전학생은 전학 첫날 약간 외로움을 느꼈다."),
    612: ("Her parents were proud of her wonderful music performance.", "부모님은 그녀의 멋진 음악 공연을 무척 자랑스러워하셨다."),
    613: ("The little girl was too shy to speak in front of the class.", "어린 소녀는 너무 수줍어서 반 친구들 앞에서 말을 하지 못했다."),
    614: ("Take a deep breath if you feel nervous before the speech.", "발표 전에 긴장이 되면 숨을 깊이 들이마시세요."),
    615: ("Try to stay calm and follow the teacher's instructions.", "침착함을 유지하고 선생님의 안내를 따르세요."),
    616: ("This beginner puzzle is easy enough for a child to solve.", "이 초보자용 퍼즐은 어린아이가 풀기에도 충분히 쉽다."),
    617: ("It is difficult to climb the steep rocky mountain in winter.", "겨울에 가파른 바위산을 오르는 것은 어렵다."),
    618: ("She explained the science concept in a simple and clear way.", "그녀는 과학 개념을 쉽고 명쾌한 방식으로 설명해 주었다."),
    619: ("It is true that honesty is the best policy in life.", "정직이 인생에서 최선의 방책이라는 말은 참이다."),
    620: ("Mark whether the statement on the worksheet is true or false.", "학습지의 진술이 참인지 거짓인지 표시하세요."),

    # 621-640 (판단 / 인기도 / 중요도)
    621: ("Turn right at the traffic lights to reach the bakery.", "빵집에 가려면 신호등에서 우회전하세요."),
    622: ("He gave the wrong answer because he misread the question.", "그는 문제를 잘못 읽어서 엉뚱한 답을 적었다."),
    623: ("The diamond in the museum display is real and precious.", "박물관 진열장에 있는 다이아몬드는 진짜이며 귀중하다."),
    624: ("Are you ready to leave for the train station?", "기차역으로 떠날 준비가 다 되었니?"),
    625: ("I am sure that you will do well on the exam.", "네가 시험을 잘 볼 것이라고 나는 확신한다."),
    626: ("The mountain stream had crystal clear water.", "산골짜기 시냇물은 수정처럼 맑은 물이 흘렀다."),
    627: ("BTS is a world-famous pop group from South Korea.", "방탄소년단은 한국 출신의 세계적으로 유명한 팝 그룹이다."),
    628: ("Soccer is the most popular sport among young students.", "축구는 어린 학생들 사이에서 가장 인기 있는 스포츠이다."),
    629: ("Today is a special day because it is my grandmother's birthday.", "오늘은 할머니의 생신이라 특별한 날이다."),
    630: ("We heard a strange rustling sound coming from the bushes.", "우리는 덤불 속에서 부스럭거리는 이상한 소리를 들었다."),
    631: ("Every culture has different holiday traditions and customs.", "문화마다 각기 다른 명절 전통과 풍습이 있다."),
    632: ("Getting enough sleep is very important for growing children.", "충분한 수면을 취하는 것은 성장기 어린이에게 매우 중요하다."),
    633: ("A passport is necessary when traveling to another country.", "다른 나라로 여행할 때는 여권이 반드시 필요하다."),
    634: ("With hard work and patience, anything is possible.", "노력과 끈기만 있다면 무엇이든 가능하다."),
    635: ("It is impossible to finish this entire project in one hour.", "이 프로젝트 전체를 한 시간 만에 끝내는 것은 불가능하다."),
    636: ("She was lucky to find an empty seat on the crowded bus.", "그녀는 만원 버스에서 빈자리를 찾아서 운이 좋았다."),
    637: ("The friendly clown told a funny joke that made everyone laugh.", "친근한 광대가 모두를 웃게 만든 재미있는 농담을 들려주었다."),
    638: ("I read an interesting science article about outer space.", "나는 우주 공간에 관한 흥미진진한 과학 기사를 읽었다."),
    639: ("The long lecture was so boring that many people dozed off.", "긴 강연이 너무 지루해서 많은 사람이 졸았다."),
    640: ("Be careful when crossing the busy road.", "복잡한 길을 건널 때는 항상 조심하세요."),

    # 641-660 (태도 / 기본 동사)
    641: ("A careless mistake on the test cost him a few points.", "시험에서 부주의한 실수 하나로 몇 점을 잃었다."),
    642: ("An honest person always tells the truth.", "정직한 사람은 언제나 진실을 말한다."),
    643: ("Saying 'please' and 'thank you' is polite and courteous.", "'부탁합니다'와 '감사합니다'라고 말하는 것은 예의 바른 행동이다."),
    644: ("A bilingual dictionary is very useful for language learners.", "이중 언어 사전은 어학 학습자에게 매우 유용하다."),
    645: ("Broken keys are completely useless for opening locks.", "부러진 열쇠는 자물쇠를 여는 데 전혀 쓸모가 없다."),
    646: ("The warm spring weather was perfect for an outdoor picnic.", "따스한 봄 날씨는 야외 소풍을 즐기기에 더할 나위 없이 완벽했다."),
    647: ("He ate the whole sandwich by himself in five minutes.", "그는 5분 만에 샌드위치 전체를 혼자 다 먹었다."),
    648: ("Cut the red apple into half and share it with your friend.", "빨간 사과를 반으로 잘라 친구와 나눠 먹어라."),
    649: ("May I have a piece of strawberry cake?", "딸기 케이크 한 조각 먹어도 될까요?"),
    650: ("Grammar is only one part of learning a new language.", "문법은 새로운 언어를 배우는 한 부분일 뿐이다."),
    651: ("Be kind and respectful to everyone you meet.", "네가 만나는 모든 사람에게 친절하고 정중하게 대하라."),
    652: ("I have a cute fluffy puppy at home.", "나는 집에 귀엽고 털이 보송보송한 강아지가 있다."),
    653: ("Please do your homework before dinner.", "저녁 식사 전에 숙제를 끝내라."),
    654: ("What did the teacher say about the school trip?", "선생님께서 현장학습에 대해 뭐라고 말씀하셨니?"),
    655: ("Let's go to the sunny park this Saturday.", "이번 주 토요일에 햇살 좋은 공원으로 놀러 가자."),
    656: ("Come here and take a look at this colorful butterfly.", "이리 와서 이 알록달록한 나비 좀 봐."),
    657: ("I can see white snow falling softly from my window.", "창문 너머로 하얀 눈이 소복소복 내리는 것이 보인다."),
    658: ("Look at that bright shooting star in the night sky.", "밤하늘에 지나가는 저 밝은 유성을 봐."),
    659: ("We gathered to watch the live fireworks display.", "우리는 라이브 불꽃놀이를 보기 위해 모였다."),
    660: ("Can you hear the crickets chirping in the garden?", "정원에서 귀뚜라미 우는 소리가 들리니?"),

    # 661-680 (감각 / 일상 행동 동사)
    661: ("Listen carefully to the flight attendant's announcement.", "승무원의 기내 안내 방송에 귀를 기울이세요."),
    662: ("I feel great after taking a warm shower.", "따뜻한 샤워를 하고 나니 기분이 정말 상쾌하다."),
    663: ("These fresh yellow roses smell wonderfully sweet.", "이 신선한 노란 장미들은 아주 향기로운 냄새가 난다."),
    664: ("The hot tomato soup tastes delicious with melted cheese.", "녹인 치즈가 들어간 따뜻한 토마토수프는 맛이 아주 좋다."),
    665: ("Please do not touch the ancient museum exhibits.", "박물관의 고대 전시물에 손을 대지 마세요."),
    666: ("Mom helped me make a birthday card for my friend.", "엄마는 내가 친구를 위한 생일 카드를 만드는 것을 도와주셨다."),
    667: ("You need to get a library card to borrow books.", "책을 빌리려면 도서관 카드를 발급받아야 한다."),
    668: ("Take a warm jacket because it will get cold tonight.", "오늘 밤 날씨가 쌀쌀해질 테니 따뜻한 겉옷을 챙겨라."),
    669: ("Please give me a glass of warm water.", "따뜻한 물 한 잔만 가져다주세요."),
    670: ("Don't forget to bring your umbrella to school today.", "오늘 학교에 우산 챙겨 가는 것을 잊지 마라."),
    671: ("He helped carry the heavy grocery bags into the kitchen.", "그는 무거운 장바구니들을 주방 안으로 옮기는 것을 도왔다."),
    672: ("I will send you a text message when I arrive at the station.", "기차역에 도착하면 문자 메시지를 보낼게."),
    673: ("She was delighted to receive a handwritten postcard.", "그녀는 손으로 쓴 엽서를 받고 몹시 기뻐했다."),
    674: ("Put your dirty dishes in the kitchen sink.", "사용한 그릇은 싱크대 안에 넣어 두어라."),
    675: ("Keep your room tidy and clean every day.", "네 방을 매일 정돈되고 깨끗하게 유지해라."),
    676: ("Hold my hand when we cross the busy street.", "복잡한 거리를 건널 때는 내 손을 꼭 잡아라."),
    677: ("Run fast and catch the flying red ball.", "빨리 달려가서 날아오는 빨간 공을 잡아라."),
    678: ("Be careful not to drop that fragile porcelain teacup.", "깨지기 쉬운 도자기 찻잔을 떨어뜨리지 않도록 조심해라."),
    679: ("Watch your step so you don't fall on the slippery ice.", "미끄러운 얼음판 위에서 넘어지지 않도록 발걸음을 조심해라."),
    680: ("Let's pick fresh sweet strawberries at the farm.", "농장에서 신선하고 달콤한 딸기를 따자."),

    # 681-700 (동작 / 상태 변화 동사)
    681: ("Pull the door open to enter the bakery.", "빵집에 들어가려면 문을 당겨서 여세요."),
    682: ("Push the elevator button for the fifth floor.", "5층으로 가려면 엘리베이터 버튼을 누르세요."),
    683: ("Throw the tennis ball for the playful puppy to chase.", "장난꾸러기 강아지가 쫓아가도록 테니스공을 던져 줘라."),
    684: ("He hit the baseball hard and ran to first base.", "그는 야구공을 강하게 치고 1루로 전력 질주했다."),
    685: ("Use scissors to cut the ribbon on the gift box.", "선물 상자의 리본을 자를 때는 가위를 사용하세요."),
    686: ("Be careful not to break the delicate glass vase.", "섬세한 유리 꽃병을 깨뜨리지 않도록 주의하세요."),
    687: ("Open the window to let the fresh morning breeze in.", "신선한 아침 산들바람이 들어오도록 창문을 열어라."),
    688: ("Remember to close the door quietly when you leave.", "나갈 때는 문을 조용히 닫는 것을 잊지 마라."),
    689: ("Please shut the window because it is raining heavily.", "비가 세차게 내리니 창문을 닫아 주세요."),
    690: ("Make sure to lock the front door when you leave home.", "집을 나설 때는 현관문을 꼭 잠그도록 해라."),
    691: ("Turn the light off before you go to sleep.", "잠자리에 들기 전에 불을 끄세요."),
    692: ("We decided to move the study desk closer to the window.", "우리는 공부 책상을 창가 쪽으로 더 가깝게 옮기기로 했다."),
    693: ("The bus will stop right in front of the community center.", "버스는 주민센터 바로 앞에 정차할 것이다."),
    694: ("The morning race will start at eight o'clock sharp.", "아침 달리기는 정확히 8시에 시작될 것이다."),
    695: ("Let's begin today's lesson with a fun vocabulary game.", "재미있는 단어 게임으로 오늘의 수업을 시작해 봅시다."),
    696: ("I must finish reading this chapter before dinner.", "저녁 식사 전에 이 장을 다 읽어야 한다."),
    697: ("The exciting movie reached its happy end.", "흥미진진한 영화가 행복한 결말을 맺었다."),
    698: ("We decided to stay indoors until the heavy rain stopped.", "우리는 폭우가 그칠 때까지 실내에 머물기로 했다."),
    699: ("Please wait for me at the station entrance.", "기차역 입구에서 나를 조금만 기다려 줘."),
    700: ("We must leave early to catch the morning train.", "아침 기차를 타려면 우리는 일찍 출발해야 한다."),

    # 701-720 (이동 / 자세 / 신체 활동 동사)
    701: ("We will arrive at the campsite before sunset.", "우리는 해가 지기 전에 캠핑장에 도착할 것이다."),
    702: ("Please take off your muddy shoes before you enter the house.", "집에 들어가기 전에 진흙 묻은 신발을 벗으세요."),
    703: ("The passenger train will pass through the green valley.", "여객 열차가 푸른 계곡을 지나갈 것이다."),
    704: ("Look both ways before you cross the busy street.", "번잡한 도로를 건너기 전에는 양쪽을 모두 살피세요."),
    705: ("Follow the wooden trail signs to reach the mountaintop.", "산 정상에 가려면 나무로 된 등산로 표지판을 따라가세요."),
    706: ("The scout leader will lead the group through the forest path.", "스카우트 대장이 숲길을 따라 무리를 이끌 것이다."),
    707: ("He can run very fast in his new sneakers.", "그는 새 운동화를 신고 아주 빠르게 달릴 수 있다."),
    708: ("We like to walk our dog in the neighborhood park.", "우리는 동네 공원에서 강아지를 산책시키는 것을 좋아한다."),
    709: ("Frogs can jump amazingly high between lily pads.", "개구리는 연잎 사이를 놀라울 정도로 높이 뛸 수 있다."),
    710: ("Migrating birds fly south when winter approaches.", "철새들은 겨울이 다가오면 남쪽으로 날아간다."),
    711: ("Fish swim effortlessly through the clear river water.", "물고기들이 맑은 강물 속을 수월하게 헤엄쳐 다닌다."),
    712: ("We decided to climb the hill to see the sunset.", "우리는 일몰을 감상하기 위해 언덕을 오르기로 했다."),
    713: ("He learned how to ride a two-wheeled bicycle last summer.", "그는 지난여름에 두 발 자전거 타는 법을 배웠다."),
    714: ("My mother drives carefully whenever it rains.", "우리 어머니는 비가 올 때마다 조심스럽게 운전하신다."),
    715: ("Please stand in a single line at the ticket booth.", "매표소 앞에 한 줄로 바르게 서 주세요."),
    716: ("Sit down on this comfortable armchair and rest your feet.", "이 편안한 안락의자에 앉아서 발을 쉬어라."),
    717: ("Lie down on the soft sofa and take a short nap.", "푹신한 소파에 누워서 잠깐 낮잠을 자라."),
    718: ("I usually sleep eight hours every night to stay healthy.", "나는 건강을 위해 매일 밤 보통 8시간씩 잔다."),
    719: ("I wake up at seven o'clock every morning to go to school.", "나는 등교를 위해 매일 아침 7시에 일어난다."),
    720: ("Eat plenty of fresh fruit and green vegetables.", "신선한 과일과 녹색 채소를 많이 드세요."),

    # 721-740 (가사 / 언어 / 감정 표현 동사)
    721: ("Drink a glass of warm water when you wake up.", "아침에 일어나면 따뜻한 물 한 잔을 마셔라."),
    722: ("Dad likes to cook a warm pot of stew on chilly evenings.", "아빠는 쌀쌀한 저녁에 따뜻한 찌개 끓이는 것을 좋아하신다."),
    723: ("Mom promised to bake a chocolate cake for my birthday.", "엄마는 내 생일에 초콜릿 케이크를 구워 주시기로 약속하셨다."),
    724: ("Wash your hands thoroughly with soap before eating.", "식사 전에는 손을 비누로 깨끗이 씻으세요."),
    725: ("Let's clean the living room together this Saturday.", "이번 주 토요일에 거실을 함께 청소하자."),
    726: ("Wear a warm woolen hat to protect your ears from the cold.", "추위로부터 귀를 보호하기 위해 따뜻한 털모자를 써라."),
    727: ("She dressed in her finest clothes for the ceremony.", "그녀는 축하 행사를 위해 가장 멋진 옷을 차려입었다."),
    728: ("He can speak both English and Korean fluently.", "그는 영어와 한국어를 둘 다 유창하게 구사할 수 있다."),
    729: ("We sat on the bench and talked about our favorite hobbies.", "우리는 벤치에 앉아 가장 좋아하는 취미에 대해 이야기했다."),
    730: ("Grandfather loved to tell us fascinating folk tales.", "할아버지는 우리에게 재미있는 전래동화를 들려주는 것을 무척 좋아하셨다."),
    731: ("Feel free to ask the teacher if you need help with math.", "수학에 도움이 필요하면 선생님께 편하게 질문해라."),
    732: ("She raised her hand to answer the teacher's question.", "그녀는 선생님의 질문에 대답하기 위해 손을 들었다."),
    733: ("I will call you on the phone as soon as I arrive home.", "집에 도착하자마자 너에게 전화할게."),
    734: ("Don't shout in the quiet library study room.", "조용한 도서관 열람실에서 소리 지르지 마라."),
    735: ("The baby began to cry because it was hungry.", "아기는 배가 고파서 울기 시작했다."),
    736: ("The funny cartoon made all the children laugh out loud.", "재미있는 만화가 모든 아이들을 활짝 웃게 만들었다."),
    737: ("She greeted her new classmates with a warm and gentle smile.", "그녀는 따뜻하고 다정한 미소로 새 반 친구들을 맞이했다."),
    738: ("I think this blue backpack is the best choice for you.", "내 생각에는 이 파란색 배낭이 너에게 가장 좋은 선택인 것 같다."),
    739: ("I know the answer to the first riddle on the page.", "나는 페이지에 있는 첫 번째 수수께끼의 정답을 알고 있다."),
    740: ("Do you understand how to use this grammar rule?", "이 문법 규칙을 어떻게 사용하는지 이해하니?"),

    # 741-760 (인지 / 감정 / 경제 동사)
    741: ("Children learn new English words quickly through songs.", "아이들은 노래를 통해 새로운 영어 단어를 빠르게 배운다."),
    742: ("Remember to turn off the lights when you leave the classroom.", "교실을 나갈 때는 불을 끄는 것을 기억하세요."),
    743: ("Don't forget to bring your gym uniform tomorrow.", "내일 체육복 가져오는 것을 잊지 마라."),
    744: ("I believe that practice leads to steady improvement.", "나는 꾸준한 연습이 지속적인 향상으로 이어진다고 믿는다."),
    745: ("I hope tomorrow is a sunny day for our school picnic.", "학교 소풍날인 내일 날씨가 맑았으면 좋겠다."),
    746: ("Make a silent wish before blowing out your birthday candles.", "생일 촛불을 불기 전에 마음속으로 소원을 빌어라."),
    747: ("What do you want to eat for lunch today?", "오늘 점심으로 무엇을 먹고 싶니?"),
    748: ("We need two more eggs to bake the sweet cookies.", "달콤한 쿠키를 구우려면 달걀 두 개가 더 필요하다."),
    749: ("I like drinking warm milk with a dash of honey.", "나는 꿀을 살짝 넣은 따뜻한 우유를 마시는 것을 좋아한다."),
    750: ("Grandmother loves tending to the colorful flowers in her garden.", "할머니는 정원의 알록달록한 꽃들을 가꾸는 것을 정말 사랑하신다."),
    751: ("Cats generally hate taking a bath in water.", "고양이는 대개 물에서 목욕하는 것을 싫어한다."),
    752: ("We truly enjoy walking along the sandy beach at sunset.", "우리는 일몰 때 모래사장을 따라 산책하는 것을 정말 즐긴다."),
    753: ("I prefer drinking warm herbal tea to iced soda.", "나는 시원한 탄산음료보다 따뜻한 허브차를 마시는 편을 더 선호한다."),
    754: ("Could you help me carry these heavy textbooks up the stairs?", "이 무거운 교과서들을 계단 위로 옮기는 것을 도와주시겠어요?"),
    755: ("Remember to save your digital document before shutting down the computer.", "컴퓨터를 끄기 전에 디지털 문서를 저장하는 것을 잊지 마세요."),
    756: ("You can use a ruler to draw a straight line on your notebook.", "공책에 곧은 직선을 긋기 위해 자를 사용할 수 있다."),
    757: ("Look carefully and you will find your lost pencil under the desk.", "책상 밑을 잘 찾아보면 잃어버린 연필을 찾을 수 있을 거야."),
    758: ("Be careful not to lose your subway transit card.", "지하철 교통카드를 잃어버리지 않도록 조심해라."),
    759: ("Our soccer team worked hard and managed to win the championship.", "우리 축구팀은 열심히 노력해서 마침내 우승을 거머쥐었다."),
    760: ("I want to buy a pair of running shoes for gym class.", "체육 시간에 신을 운동화 한 켤레를 사고 싶다."),

    # 761-780 (거래 / 상호작용 / 사회적 예절 동사)
    761: ("The local market stalls sell fresh fruits and vegetables.", "동네 시장 가판대에서는 신선한 과일과 채소를 판매한다."),
    762: ("You can pay for your groceries with cash or a card.", "식료품 대금은 현금이나 카드로 결제하실 수 있습니다."),
    763: ("How much does this cute plush bear cost?", "이 귀여운 봉제 곰 인형은 가격이 얼마인가요?"),
    764: ("Don't spend all your pocket money on sweets.", "용돈을 전부 사탕 사는 데 다 써 버리지 마라."),
    765: ("They work diligently to keep the neighborhood park tidy.", "그들은 동네 공원을 깨끗하게 유지하기 위해 부지런히 일한다."),
    766: ("Always try your best even when the task seems challenging.", "일이 어려워 보일 때라도 항상 최선을 다해 보세요."),
    767: ("You should change out of your wet clothes immediately.", "젖은 옷은 즉시 갈아입어야 한다."),
    768: ("Sunflower seeds grow rapidly in warm sunshine and water.", "해바라기 씨앗은 따뜻한 햇살과 물을 받으면 쑥쑥 자란다."),
    769: ("Many different animals live peacefully in the national forest.", "국립 산림 속에는 다양한 동물들이 평화롭게 살고 있다."),
    770: ("House plants will die if they don't get enough water.", "실내 화분은 물을 충분히 주지 않으면 시들어 죽는다."),
    771: ("Cold winter frosts can kill delicate garden flowers.", "매서운 겨울 서리는 연약한 화원의 꽃들을 얼려 죽일 수 있다."),
    772: ("Siblings should learn to share toys rather than fight.", "형제자매는 싸우기보다는 장난감을 나눠 쓰는 법을 배워야 한다."),
    773: ("Let's meet at the library front door at three o'clock.", "오후 3시에 도서관 정문 앞에서 만나자."),
    774: ("Would you like to join our school badminton club?", "우리 학교 배드민턴 동아리에 가입할래?"),
    775: ("I want to invite all my classmates to my birthday party.", "내 생일 파티에 반 친구들을 모두 초대하고 싶다."),
    776: ("We plan to visit our grandparents during the holiday weekend.", "우리는 연휴 주말 동안 조부모님 댁을 방문할 계획이다."),
    777: ("The friendly host came out to welcome the guests warmly.", "친절한 주인이 손님들을 따뜻하게 맞이하러 나왔다."),
    778: ("Always remember to thank people who offer you help.", "도움을 주는 분들에게는 항상 감사 인사를 전하는 것을 잊지 마세요."),
    779: ("Excuse me, could you tell me where the nearest pharmacy is?", "실례합니다만, 가장 가까운 약국이 어디인지 알려주시겠어요?"),
    780: ("I am so sorry for arriving late to the study meeting.", "스터디 모임에 늦게 도착해서 정말 죄송합니다."),

    # 781-800 (결정 / 공유 / 제작 동사)
    781: ("Please pass me the salt shaker across the dining table.", "식탁 건너편에 있는 소금통 좀 건네주세요."),
    782: ("I agree with your suggestion to hold a picnic in the park.", "공원에서 소풍을 열자는 당신의 제안에 전적으로 동의합니다."),
    783: ("He politely refused the offer of a second slice of cake.", "그는 케이크 한 조각을 더 주겠다는 권유를 정중히 사양했다."),
    784: ("The school rules do not allow smartphones during class.", "교칙상 수업 중에는 스마트폰 사용이 허용되지 않는다."),
    785: ("You can choose your favorite flavor of ice cream.", "가장 좋아하는 맛의 아이스크림을 골라 보세요."),
    786: ("They will decide on a travel destination after looking at brochures.", "그들은 여행 책자를 살펴본 후 여행지를 결정할 것이다."),
    787: ("We plan to spend our summer vacation by the seaside.", "우리는 여름휴가를 바닷가에서 보낼 계획이다."),
    788: ("Mom helped me prepare a delicious lunchbox for the field trip.", "엄마는 내가 현장학습 때 가져갈 맛있는 도시락을 준비하는 것을 도와주셨다."),
    789: ("Could you show me how to solve this difficult puzzle?", "이 어려운 퍼즐을 어떻게 푸는지 보여주시겠어요?"),
    790: ("The playful squirrel ran to hide an acorn under the leaves.", "장난꾸러기 다람쥐가 낙엽 밑에 도토리를 숨기려고 달려갔다."),
    791: ("Cover the warm soup pot with a lid to keep heat inside.", "온기를 유지할 수 있도록 따뜻한 국 냄비를 뚜껑으로 덮어라."),
    792: ("Fill the water bottle up to the top line.", "물병의 맨 위 표시선까지 물을 채우세요."),
    793: ("Please empty the recycling bin into the outdoor container.", "재활용 분리수거함을 야외 수거함에 비워 주세요."),
    794: ("Children should share their toys and take turns playing.", "아이들은 장난감을 서로 나누어 쓰고 번갈아 가며 놀아야 한다."),
    795: ("Could you please lend me your eraser for a minute?", "지우개 좀 잠깐 빌려주실 수 있나요?"),
    796: ("May I borrow your blue pen to write down a quick note?", "간단한 메모를 적으려고 하는데 파란색 펜 좀 빌릴 수 있을까요?"),
    797: ("Don't forget to return the library books by Friday afternoon.", "금요일 오후까지 도서관 책을 반납하는 것을 잊지 마세요."),
    798: ("Dad helped me fix the loose chain on my bicycle.", "아빠는 내 자전거의 헐거워진 체인을 고치는 것을 도와주셨다."),
    799: ("The little boys used colorful blocks to build a tall fortress.", "어린 소년들은 알록달록한 블록으로 높은 요새를 쌓아 올렸다."),
    800: ("We decided to paint the wooden garden chair a bright sky blue.", "우리는 나무 정원 의자를 밝은 하늘색으로 칠하기로 했다."),
}
