# -*- coding: utf-8 -*-
"""
Level 1 정통 맞춤형 예문 데이터 Part 1 (단어 1 ~ 200)
초등/기초(A1~A2) 수준의 자연스러운 일상 회화 문장 및 매끄러운 한국어 번역
"""

PART1_SENTENCES = {
    # 1-20 (대명사 / 의문사 / 한정사)
    1: ("I am a middle school student.", "나는 중학생이다."),
    2: ("Are you ready to go to the park?", "공원에 갈 준비 되었니?"),
    3: ("He is my best friend at school.", "그는 학교에서 나의 가장 친한 친구이다."),
    4: ("She has a warm and bright smile.", "그녀는 따뜻하고 밝은 미소를 가지고 있다."),
    5: ("It is raining heavily outside.", "밖에 비가 세차게 내리고 있다."),
    6: ("We study English together every afternoon.", "우리는 매일 오후에 함께 영어를 공부한다."),
    7: ("They are playing soccer in the playground.", "그들은 운동장에서 축구를 하고 있다."),
    8: ("This is my favorite storybook.", "이것은 내가 가장 좋아하는 동화책이다."),
    9: ("Look at that tall tree over there.", "저기 있는 저 키 큰 나무를 봐."),
    10: ("These sweet strawberries are delicious.", "이 달콤한 딸기들은 아주 맛있다."),
    11: ("Those shoes in the shop look comfortable.", "가게에 있는 저 신발들은 편해 보인다."),
    12: ("What would you like to drink?", "무엇을 마시고 싶으세요?"),
    13: ("Who is that boy standing by the window?", "창가에 서 있는 저 소년은 누구니?"),
    14: ("Where did you put my notebook?", "내 공책을 어디에 두었니?"),
    15: ("When does the summer vacation start?", "여름 방학은 언제 시작하니?"),
    16: ("Why are you so happy today?", "오늘 왜 그렇게 기분이 좋니?"),
    17: ("How do you usually come to school?", "너는 보통 학교에 어떻게 오니?"),
    18: ("All children love to play outside.", "모든 아이들은 밖에서 노는 것을 좋아한다."),
    19: ("Would you like some warm milk?", "따뜻한 우유 좀 마실래?"),
    20: ("Do you have any questions about this story?", "이 이야기에 대해 궁금한 점이 있니?"),

    # 21-40 (수량사 / 접속사 / 전치사)
    21: ("There are many colorful flowers in the garden.", "정원에 알록달록한 꽃이 많이 있다."),
    22: ("How much water do you drink every day?", "너는 매일 물을 얼마나 많이 마시니?"),
    23: ("She walks her dog every morning.", "그녀는 매일 아침 강아지를 산책시킨다."),
    24: ("Do you have another color for this shirt?", "이 셔츠 다른 색상도 있나요?"),
    25: ("We go to the same school.", "우리는 같은 학교에 다닌다."),
    26: ("I like bread and cheese for breakfast.", "나는 아침 식사로 빵과 치즈를 좋아한다."),
    27: ("He ran fast, but he missed the bus.", "그는 빨리 달렸지만 버스를 놓쳤다."),
    28: ("Would you prefer tea or juice?", "차와 주스 중 어떤 것을 드시겠어요?"),
    29: ("It was very hot, so we stayed indoors.", "날씨가 너무 더워서 우리는 실내에 머물렀다."),
    30: ("I stayed at home because it rained all day.", "하루 종일 비가 와서 나는 집에 머물렀다."),
    31: ("Call me if you need any help.", "도움이 필요하면 언제든 전화해."),
    32: ("She works as an English teacher.", "그녀는 영어 교사로 일한다."),
    33: ("Let's meet at the front gate at two o'clock.", "2시에 정문 앞에서 만나자."),
    34: ("The cat is sleeping in a cardboard box.", "고양이가 상자 안에서 자고 있다."),
    35: ("There is a cup of hot cocoa on the desk.", "책상 위에 따뜻한 코코아 한 잔이 놓여 있다."),
    36: ("We walked to the central station.", "우리는 중앙역까지 걸어갔다."),
    37: ("This birthday gift is for you.", "이 생일 선물은 너를 위한 거야."),
    38: ("Where are you from?", "어느 나라에서 오셨나요?"),
    39: ("Can you come to the party with me?", "나랑 같이 파티에 갈 수 있니?"),
    40: ("She sat quietly by the window.", "그녀는 창가 옆에 조용히 앉아 있었다."),

    # 41-60 (전치사 / 숫자)
    41: ("This is a photo of my family.", "이것은 우리 가족의 사진이다."),
    42: ("Tell me about your favorite movie.", "네가 가장 좋아하는 영화에 대해 이야기해 줘."),
    43: ("The dog jumped into the clear water.", "강아지가 맑은 물속으로 뛰어들었다."),
    44: ("Birds were flying over the green hills.", "새들이 푸른 언덕 위를 날고 있었다."),
    45: ("My puppy is hiding under the bed.", "우리 강아지가 침대 밑에 숨어 있다."),
    46: ("We usually play basketball after school.", "우리는 보통 방과 후에 농구를 한다."),
    47: ("Please wash your hands before dinner.", "저녁 식사 전에 손을 씻으세요."),
    48: ("The post office is between the bank and the bakery.", "우체국은 은행과 빵집 사이에 있다."),
    49: ("The train passed through the long dark tunnel.", "기차가 길고 어두운 터널을 통과했다."),
    50: ("He went to school without his umbrella.", "그는 우산 없이 학교에 갔다."),
    51: ("There is only one apple left in the bowl.", "그릇에 사과가 딱 하나 남아 있다."),
    52: ("I have two older brothers.", "나에게는 형이 두 명 있다."),
    53: ("The flag has three different colors.", "그 깃발은 세 가지 다른 색을 띠고 있다."),
    54: ("A table usually has four legs.", "탁자는 보통 다리가 네 개 있다."),
    55: ("High five! We won the game!", "하이파이브! 우리가 경기에서 이겼어!"),
    56: ("There are six eggs in the carton.", "달걀 한 판에 달걀 여섯 개가 들어 있다."),
    57: ("There are seven days in a week.", "일주일은 7일이다."),
    58: ("An octopus has eight arms.", "문어는 다리가 여덟 개 있다."),
    59: ("My sister is nine years old.", "내 여동생은 아홉 살이다."),
    60: ("I have ten pencils in my pencil case.", "내 필통에는 연필이 열 자루 들어 있다."),

    # 61-80 (숫자 / 시간 / 날짜)
    61: ("Soccer teams have eleven players on the field.", "축구 팀은 경기장에 11명의 선수가 뛴다."),
    62: ("There are twelve months in one year.", "1년은 열두 달이다."),
    63: ("A teenager becomes thirteen years old.", "만 13세가 되면 십 대가 된다."),
    64: ("He celebrated his fourteenth birthday yesterday.", "그는 어제 14번째 생일을 맞이했다."),
    65: ("The bus arrives in fifteen minutes.", "버스는 15분 뒤에 도착한다."),
    66: ("There are twenty students in our English class.", "우리 영어 수업에는 학생이 20명 있다."),
    67: ("My uncle is thirty years old.", "우리 삼촌은 서른 살이다."),
    68: ("The speed limit here is forty kilometers per hour.", "여기 제한 속도는 시속 40킬로미터이다."),
    69: ("My grandmother lived in this house for fifty years.", "우리 할머니는 이 집에서 50년 동안 사셨다."),
    70: ("The puzzle has one hundred pieces.", "그 퍼즐은 100조각으로 이루어져 있다."),
    71: ("More than a thousand people came to the concert.", "천 명이 넘는 사람들이 콘서트에 왔다."),
    72: ("Today is my first day at middle school.", "오늘은 나의 중학교 첫날이다."),
    73: ("She won second place in the speech contest.", "그녀는 웅변대회에서 2등을 차지했다."),
    74: ("Our classroom is on the third floor.", "우리 교실은 3층에 있다."),
    75: ("What time does the morning concert begin?", "오전 콘서트는 몇 시에 시작하나요?"),
    76: ("Today is a sunny and pleasant day.", "오늘은 화창하고 기분 좋은 날이다."),
    77: ("I visit my grandparents once a week.", "나는 일주일에 한 번 조부모님 댁을 방문한다."),
    78: ("February is the shortest month of the year.", "2월은 일 년 중 가장 짧은 달이다."),
    79: ("Happy New Year to everyone!", "모두 새해 복 많이 받으세요!"),
    80: ("What are you planning to do today?", "오늘 무엇을 할 계획이니?"),

    # 81-100 (날짜 / 계절 / 요일)
    81: ("I will return your comic book tomorrow.", "내일 네 만화책 돌려줄게."),
    82: ("It rained heavily yesterday afternoon.", "어제 오후에 비가 많이 내렸다."),
    83: ("Good morning! Did you sleep well?", "좋은 아침이에요! 잘 잤나요?"),
    84: ("Let's play tennis together this afternoon.", "오늘 오후에 같이 테니스 치자."),
    85: ("We watch a movie together in the evening.", "우리는 저녁에 함께 영화를 본다."),
    86: ("The stars shine brightly in the night sky.", "밤하늘에 별들이 밝게 빛난다."),
    87: ("The trip takes about one hour by train.", "기차로 약 한 시간 정도 걸린다."),
    88: ("Wait a minute, I forgot my keys.", "잠깐만 기다려 봐, 열쇠를 두고 왔어."),
    89: ("The wall clock says it is three o'clock.", "벽시계가 3시를 가리키고 있다."),
    90: ("I marked my birthday on the wall calendar.", "나는 벽걸이 달력에 내 생일을 표시해 두었다."),
    91: ("Flowers start to bloom in early spring.", "초봄에는 꽃들이 피기 시작한다."),
    92: ("We often go to the beach in summer.", "우리는 여름에 자주 바닷가에 간다."),
    93: ("The leaves turn red and yellow in autumn.", "가을에는 나뭇잎이 붉고 노랗게 물든다."),
    94: ("It snows a lot here in winter.", "이곳은 겨울에 눈이 많이 내린다."),
    95: ("Spring is my favorite season of the year.", "봄은 내가 일 년 중 가장 좋아하는 계절이다."),
    96: ("We usually go on a family picnic on Sunday.", "우리는 보통 일요일에 가족 소풍을 간다."),
    97: ("The school week begins on Monday morning.", "학교 수업 주는 월요일 아침에 시작된다."),
    98: ("We have physical education class on Tuesday.", "우리는 화요일에 체육 수업이 있다."),
    99: ("The art club meets every Wednesday after school.", "미술 동아리는 매주 수요일 방과 후에 모인다."),
    100: ("Thursday is our library reading day.", "목요일은 도서관에서 책을 읽는 날이다."),

    # 101-120 (요일 / 사람 / 가족)
    101: ("Everyone is happy when Friday arrives.", "금요일이 오면 모두가 신나 한다."),
    102: ("I clean my bedroom every Saturday morning.", "나는 매주 토요일 아침에 내 방을 청소한다."),
    103: ("She is a very polite and helpful person.", "그녀는 매우 예의 바르고 친절한 사람이다."),
    104: ("Many people are waiting for the bus.", "많은 사람들이 버스를 기다리고 있다."),
    105: ("The tall man helped carry my heavy bag.", "키 큰 남자가 내 무거운 가방을 들어주었다."),
    106: ("A kind woman gave me directions to the station.", "친절한 여성분이 역으로 가는 길을 알려주셨다."),
    107: ("The little boy is flying a colorful kite.", "어린 소년이 알록달록한 연을 날리고 있다."),
    108: ("The girl has a bright smile and long hair.", "그 소녀는 환한 미소와 긴 머리를 가지고 있다."),
    109: ("The sweet baby fell asleep in the crib.", "귀여운 아기가 요람에서 잠이 들었다."),
    110: ("Every child loves hearing bedtime stories.", "모든 아이는 잠자리 동화 듣는 것을 좋아한다."),
    111: ("The children are playing happily in the park.", "아이들이 공원에서 즐겁게 놀고 있다."),
    112: ("Every parent wants the best for their children.", "모든 부모는 자녀를 위해 최선을 다하고 싶어 한다."),
    113: ("My father cooks delicious spaghetti on weekends.", "우리 아버지는 주말마다 맛있는 스파게티를 만들어 주신다."),
    114: ("My mother reads me a bedtime story every night.", "우리 어머니는 매일 밤 나에게 동화책을 읽어 주신다."),
    115: ("Dad taught me how to ride a bicycle.", "아빠가 나에게 자전거 타는 법을 가르쳐 주셨다."),
    116: ("Mom baked warm chocolate cookies for us.", "엄마가 우리를 위해 따뜻한 초콜릿 쿠키를 구워 주셨다."),
    117: ("Their son wants to become a pilot.", "그들의 아들은 비행기 조종사가 되고 싶어 한다."),
    118: ("Their daughter plays the piano very well.", "그들의 딸은 피아노를 아주 잘 친다."),
    119: ("My older brother helps me with my homework.", "우리 형은 내 숙제를 도와준다."),
    120: ("My little sister loves drawing pictures.", "내 여동생은 그림 그리는 것을 정말 좋아한다."),

    # 121-140 (가족 / 신체)
    121: ("My grandfather tells interesting stories about the past.", "우리 할아버지는 과거에 대한 흥미로운 이야기를 들려주신다."),
    122: ("My grandmother knits warm sweaters for the winter.", "우리 할머니는 겨울을 위해 따뜻한 스웨터를 떠 주신다."),
    123: ("My uncle took us to the baseball game.", "삼촌이 우리를 야구장에 데려가 주셨다."),
    124: ("My aunt gave me a lovely book for my birthday.", "이모가 내 생일 선물로 예쁜 책을 주셨다."),
    125: ("I like to play board games with my cousin.", "나는 사촌과 보드게임 하는 것을 좋아한다."),
    126: ("A true friend is always there to support you.", "진정한 친구는 언제나 곁에서 응원해 준다."),
    127: ("Our neighbor has a very friendly dog.", "우리 이웃집에는 아주 다정한 강아지가 산다."),
    128: ("Drinking enough water keeps your body healthy.", "물을 충분히 마시면 몸이 건강하게 유지된다."),
    129: ("He nodded his head to show he agreed.", "그는 동의한다는 뜻으로 고개를 끄덕였다."),
    130: ("She has curly brown hair and bright eyes.", "그녀는 곱슬거리는 갈색 머리와 밝은 눈을 가지고 있다."),
    131: ("Wash your face with warm water every morning.", "매일 아침 따뜻한 물로 세수하세요."),
    132: ("She has big blue eyes and long eyelashes.", "그녀는 큰 파란 눈과 긴 속눈썹을 가지고 있다."),
    133: ("Listen carefully with your own ears.", "너의 귀로 주의 깊게 잘 들어 봐."),
    134: ("A dog has a very sensitive nose for smells.", "강아지는 냄새를 맡는 데 매우 민감한 코를 가지고 있다."),
    135: ("Cover your mouth when you cough.", "기침할 때는 입을 가리세요."),
    136: ("She put lip balm on her dry lips.", "그녀는 건조한 입술에 립밤을 발랐다."),
    137: ("A baby got its first tooth today.", "아기에게 오늘 첫 이가 났다."),
    138: ("Brush your teeth after every meal.", "식사 후에는 항상 이를 닦으세요."),
    139: ("She wore a warm woolen scarf around her neck.", "그녀는 목에 따뜻한 털목도리를 둘렀다."),
    140: ("He carried the heavy backpack on his shoulder.", "그는 무거운 배낭을 어깨에 멨다."),

    # 141-160 (신체 / 건강)
    141: ("She raised her arm to answer the question.", "그녀는 질문에 대답하기 위해 팔을 들었다."),
    142: ("Wash your hands thoroughly before eating.", "식사 전에는 손을 깨끗이 씻으세요."),
    143: ("He pointed at the picture with his finger.", "그는 손가락으로 그림을 가리켰다."),
    144: ("He gave a thumbs-up to show good job.", "그는 잘했다는 뜻으로 엄지손가락을 치켜세웠다."),
    145: ("He took a deep breath and expanded his chest.", "그는 숨을 깊이 들이쉬며 가슴을 폈다."),
    146: ("Lie down on your back and relax.", "등을 대고 누워서 편안히 쉬어라."),
    147: ("My legs are tired after walking up the stairs.", "계단을 걸어 올라갔더니 다리가 피곤하다."),
    148: ("He hurt his knee while playing basketball.", "그는 농구를 하다가 무릎을 다쳤다."),
    149: ("I stepped forward with my left foot.", "나는 왼발을 앞으로 내디뎠다."),
    150: ("Take off your shoes and wipe your feet.", "신발을 벗고 발을 닦으세요."),
    151: ("Wiggle your toes inside your warm socks.", "따뜻한 양말 안에서 발가락을 꼼지락거려 봐."),
    152: ("Sunscreen protects your skin from the bright sun.", "자외선 차단제는 뜨거운 햇볕으로부터 피부를 보호해 준다."),
    153: ("Her heart was beating fast with excitement.", "그녀의 심장은 흥분으로 빠르게 뛰고 있었다."),
    154: ("Blood delivers oxygen throughout the whole body.", "혈액은 온몸으로 산소를 전달한다."),
    155: ("Drinking milk helps build strong bones.", "우유를 마시면 뼈가 튼튼해진다."),
    156: ("She spoke in a gentle and calm voice.", "그녀는 다정하고 차분한 목소리로 말했다."),
    157: ("Eating fresh fruits is essential for good health.", "신선한 과일을 먹는 것은 건강에 필수적이다."),
    158: ("He stayed home from school because he felt sick.", "그는 몸이 아파서 학교에 가지 않고 집에 머물렀다."),
    159: ("The doctor took care of the ill child.", "의사는 아픈 아이를 정성껏 보살폈다."),
    160: ("The medicine helped relieve her headache pain.", "약이 그녀의 두통 통증을 가라앉히는 데 도움이 되었다."),

    # 161-180 (의료 / 음식 / 음료)
    161: ("Take this medicine after eating your breakfast.", "아침 식사를 한 후에 이 약을 드세요."),
    162: ("The doctor examined the patient carefully.", "의사는 환자를 꼼꼼하게 진찰했다."),
    163: ("The nurse checked my body temperature kindly.", "간호사 선생님이 친절하게 내 체온을 측정해 주셨다."),
    164: ("They rushed the injured player to the hospital.", "그들은 부상당한 선수를 서둘러 병원으로 데려갔다."),
    165: ("Korean food is known for its rich flavors.", "한국 음식은 풍부한 맛으로 유명하다."),
    166: ("Always drink a glass of fresh water in the morning.", "아침에는 항상 신선한 물 한 잔을 마셔라."),
    167: ("He poured cold milk over his morning cereal.", "그는 아침 시리얼에 시원한 우유를 부었다."),
    168: ("Fresh orange juice tastes sweet and tangy.", "신선한 오렌지 주스는 달콤하고 상큼하다."),
    169: ("Would you care for a warm cup of green tea?", "따뜻한 녹차 한 잔 드시겠습니까?"),
    170: ("My parents enjoy drinking hot coffee in the morning.", "부모님은 아침에 따뜻한 커피 마시는 것을 즐기신다."),
    171: ("We bought freshly baked bread from the bakery.", "우리는 빵집에서 갓 구운 신선한 빵을 샀다."),
    172: ("Rice is the main staple food in Korea.", "쌀은 한국의 주식이다."),
    173: ("We grilled meat for dinner on the weekend.", "우리는 주말 저녁으로 고기를 구워 먹었다."),
    174: ("My uncle ordered a juicy beef steak.", "삼촌은 육즙이 풍부한 쇠고기 스테이크를 주문했다."),
    175: ("This restaurant is famous for grilled pork belly.", "이 식당은 삼겹살 구이로 유명하다."),
    176: ("We ordered crispy fried chicken for the party.", "우리는 파티를 위해 바삭한 프라이드치킨을 주문했다."),
    177: ("We watched colorful fish swimming in the sea.", "우리는 바다에서 헤엄치는 알록달록한 물고기들을 보았다."),
    178: ("I like my fried egg with a little salt.", "나는 소금을 약간 뿌린 달걀프라이를 좋아한다."),
    179: ("She added melted cheese to the hot sandwich.", "그녀는 따뜻한 샌드위치에 녹인 치즈를 넣었다."),
    180: ("Spread a little butter on the warm toast.", "따뜻한 토스트 위에 버터를 살짝 바르세요."),

    # 181-200 (양념 / 간식 / 과일)
    181: ("Do you take sugar in your afternoon tea?", "오후에 드시는 차에 설탕을 넣으시나요?"),
    182: ("A pinch of salt makes the soup taste better.", "소금 한 꼬집이 국물 맛을 훨씬 좋게 해 준다."),
    183: ("He sprinkled black pepper on the scrambled eggs.", "그는 스크램블드에그 위에 후추를 뿌렸다."),
    184: ("A bowl of warm vegetable soup is comforting in winter.", "겨울에는 따뜻한 야채수프 한 그릇이 위로가 된다."),
    185: ("She made a fresh green salad for lunch.", "그녀는 점심으로 신선한 채소 샐러드를 만들었다."),
    186: ("I packed a ham and cheese sandwich for the picnic.", "나는 소풍을 위해 햄 치즈 샌드위치를 쌌다."),
    187: ("We blew out the candles on the birthday cake.", "우리는 생일 케이크 위의 촛불을 불어 껐다."),
    188: ("Mom baked sweet chocolate chip cookies for dessert.", "엄마가 디저트로 달콤한 초코칩 쿠키를 구워 주셨다."),
    189: ("Don't eat too much sweet candy before dinner.", "저녁 식사 전에 단 사탕을 너무 많이 먹지 마라."),
    190: ("Dark chocolate tastes slightly bitter but rich.", "다크초콜릿은 약간 쌉싸름하지만 풍미가 깊다."),
    191: ("Please put some ice cubes in my glass of juice.", "내 주스 잔에 얼음 조각 몇 개를 넣어 줘."),
    192: ("We had vanilla ice cream on a warm sunny day.", "우리는 따뜻하고 맑은 날에 바닐라 아이스크림을 먹었다."),
    193: ("Fresh fruit provides plenty of vitamins for your body.", "신선한 과일은 몸에 풍부한 비타민을 공급해 준다."),
    194: ("She peeled an apple and sliced it into pieces.", "그녀는 사과를 깎아 여러 조각으로 잘랐다."),
    195: ("Monkeys love to eat sweet yellow bananas.", "원숭이는 달콤한 노란 바나나를 즐겨 먹는다."),
    196: ("I drank a glass of freshly squeezed orange juice.", "나는 갓 짠 신선한 오렌지 주스 한 잔을 마셨다."),
    197: ("These purple grapes are sweet and juicy.", "이 보라색 포도는 달콤하고 과즙이 풍부하다."),
    198: ("We picked red ripe strawberries on the farm.", "우리는 농장에서 빨갛게 잘 익은 딸기를 땄다."),
    199: ("Add a slice of fresh lemon to the iced tea.", "아이스티에 신선한 레몬 한 조각을 띄우세요."),
    200: ("Cold watermelon is the most popular fruit in summer.", "시원한 수박은 여름철에 가장 인기 있는 과일이다."),
}
