# -*- coding: utf-8 -*-
"""
Level 1 정통 맞춤형 예문 데이터 Part 5 (단어 801 ~ 1000)
초등/기초(A1~A2) 수준의 자연스러운 일상 회화 문장 및 매끄러운 한국어 번역
"""

PART5_SENTENCES = {
    # 801-820 (시간 / 빈도 부사 / 위치)
    801: ("We are ready to leave for the park right now.", "우리는 지금 당장 공원으로 떠날 준비가 되어 있다."),
    802: ("We finished our homework and then went out to play.", "우리는 숙제를 마친 다음 밖으로 놀러 나갔다."),
    803: ("The spring flowers will bloom very soon.", "머지않아 곧 봄꽃들이 활짝 필 것이다."),
    804: ("He has already finished eating his morning breakfast.", "그는 이미 아침 식사를 다 마쳤다."),
    805: ("The baby is still asleep in the cozy crib.", "아기는 아늑한 요람에서 아직도 자고 있다."),
    806: ("The morning delivery has not arrived yet.", "아침 배송 물품이 아직 도착하지 않았다."),
    807: ("Could you please explain that grammar rule once again?", "그 문법 규칙을 다시 한번 설명해 주시겠어요?"),
    808: ("I have visited that theme park once with my family.", "나는 가족들과 함께 그 놀이공원에 한 번 가 본 적이 있다."),
    809: ("Brush your teeth at least twice a day.", "하루에 최소 두 번은 이를 닦으세요."),
    810: ("She always carries a small water bottle in her bag.", "그녀는 항상 가방에 작은 물병을 넣고 다닌다."),
    811: ("We usually eat dinner together as a family at seven.", "우리는 보통 7시에 온 가족이 함께 모여 저녁을 먹는다."),
    812: ("I often go jogging along the river on weekend mornings.", "나는 주말 아침에 강변을 따라 자주 조깅하러 간다."),
    813: ("Sometimes it snows heavily here in late March.", "이곳에는 때때로 3월 하순에 눈이 많이 내리기도 한다."),
    814: ("He seldom drinks sugary soft drinks because of his health.", "그는 건강 때문에 설탕이 든 탄산음료를 좀처럼 마시지 않는다."),
    815: ("Never forget to look both ways before crossing the road.", "길을 건너기 전에는 좌우를 살피는 것을 절대 잊지 마라."),
    816: ("Have you ever seen a shooting star at night?", "밤에 별똥별을 본 적이 있니?"),
    817: ("Please come here and sit down next to me.", "이리 와서 내 옆에 앉아라."),
    818: ("Look over there at that tall cherry tree.", "저기 있는 저 키 큰 벚나무를 봐."),
    819: ("The subway station is quite near my apartment.", "지하철역은 우리 아파트에서 꽤 가깝다."),
    820: ("The airport is far away from the city center.", "공항은 도심에서 멀리 떨어져 있다."),

    # 821-840 (방향 / 공간 / 방위)
    821: ("The frightened bird flew away into the blue sky.", "겁먹은 새가 푸른 하늘 속으로 훨훨 날아가 버렸다."),
    822: ("Please put the storybook back on the shelf after reading.", "책을 다 읽은 후에는 책꽂이 제자리에 다시 꽂아 두세요."),
    823: ("Look up at the fluffy white clouds in the sky.", "하늘에 떠 있는 몽실몽실한 흰 구름을 올려다보아라."),
    824: ("Sit down on the wooden bench and relax for a while.", "나무 벤치에 앉아서 잠시 편안히 쉬어라."),
    825: ("The keys are kept safely in my jacket pocket.", "열쇠는 내 재킷 주머니 속에 안전하게 들어 있다."),
    826: ("Let's go out and enjoy the warm sunshine in the garden.", "정원에 나가서 따스한 햇볕을 즐기자."),
    827: ("It was warm and cozy inside the cabin during the snow.", "눈이 내리는 동안 오두막 안은 따뜻하고 아늑했다."),
    828: ("The children love running outside on sunny afternoons.", "아이들은 화창한 오후에 밖에서 뛰어노는 것을 무척 좋아한다."),
    829: ("We gathered in front of the school gate for the group photo.", "우리는 단체 사진을 찍기 위해 학교 정문 앞에 모였다."),
    830: ("He walked along the sunny side of the street.", "그는 거리의 볕이 잘 드는 쪽을 따라 걸었다."),
    831: ("We climbed to the very top of the mountain to see the view.", "우리는 풍경을 보기 위해 산 맨 꼭대기까지 올라갔다."),
    832: ("There is a small secret drawer at the bottom of the desk.", "책상 맨 아래쪽에 작은 비밀 서랍이 하나 있다."),
    833: ("The town square is located in the center of the village.", "마을 광장은 마을 중심부에 위치해 있다."),
    834: ("The soccer ball landed right in the middle of the field.", "축구공이 운동장 정한가운데에 똑 떨어졌다."),
    835: ("Raise your left hand if you know the answer.", "정답을 아시는 분은 왼손을 들어 주세요."),
    836: ("Turn right at the bakery to find the community post office.", "동네 우체국을 찾으려면 빵집에서 우회전하세요."),
    837: ("Migrating birds fly north when spring returns.", "봄이 돌아오면 철새들은 북쪽으로 날아간다."),
    838: ("We traveled south to enjoy the warm beach climate.", "우리는 따뜻한 해변 기후를 즐기기 위해 남쪽으로 여행을 떠났다."),
    839: ("The golden sun rises in the east every morning.", "황금빛 태양은 매일 아침 동쪽에서 떠오른다."),
    840: ("The sun sets gracefully in the west at dusk.", "해 질 무렵 태양은 서쪽으로 우아하게 진다."),

    # 841-860 (정도 부사 / 특별한 날 / 여행)
    841: ("This homemade vegetable soup is very delicious.", "이 집에서 끓인 야채수프는 정말 맛있다."),
    842: ("The water in the kettle was too hot to drink immediately.", "주전자 속의 물은 당장 마시기에는 너무 뜨거웠다."),
    843: ("The neighborhood is quite peaceful and safe at night.", "동네는 밤에 꽤 평화롭고 안전하다."),
    844: ("I have almost finished reading my English textbook.", "나는 영어 교과서를 거의 다 읽었다."),
    845: ("We have enough warm blankets for all the guests.", "우리는 모든 손님을 위한 충분한 양의 따뜻한 담요가 있다."),
    846: ("We worked together to complete the school art project.", "우리는 학교 미술 과제를 완성하기 위해 힘을 합쳐 함께 일했다."),
    847: ("He prefers walking alone in the quiet forest trail.", "그는 조용한 숲길을 혼자 걷는 것을 더 선호한다."),
    848: ("She is the only student who got a perfect test score.", "그녀는 시험에서 만점을 받은 유일한 학생이다."),
    849: ("I just arrived at the subway station two minutes ago.", "나는 불과 2분 전에 지하철역에 막 도착했다."),
    850: ("Even young children can easily learn to use this app.", "어린아이들조차도 이 앱의 사용법을 쉽게 배울 수 있다."),
    851: ("Please write your full name clearly on the worksheet.", "학습지 위에 당신의 성명을 또렷하게 적어 주세요."),
    852: ("What is the average age of the students in your class?", "너희 반 학생들의 평균 나이는 몇 살이니?"),
    853: ("Happy birthday! Wishing you a wonderful year ahead!", "생일 축하해! 앞으로 멋진 한 해가 되기를 바랄게!"),
    854: ("We attended a lively surprise birthday party for our friend.", "우리는 친구를 위한 활기찬 깜짝 생일 파티에 참석했다."),
    855: ("She received a lovely gift wrapped in shiny red paper.", "그녀는 반짝이는 빨간 종이에 포장된 예쁜 선물을 받았다."),
    856: ("Dad brought home a surprise present for the family.", "아빠는 가족들을 위해 깜짝 선물을 집으로 가져오셨다."),
    857: ("Chuseok is a major traditional holiday celebrated in Korea.", "추석은 한국에서 기념하는 주요 전통 명절이다."),
    858: ("We plan to go camping during our summer vacation.", "우리는 여름 방학 동안 캠핑을 갈 계획이다."),
    859: ("Our family went on a memorable weekend road trip.", "우리 가족은 잊지 못할 주말 드라이브 여행을 떠났다."),
    860: ("We booked a guided walking tour of the historic palace.", "우리는 유서 깊은 고궁의 가이드 도보 투어를 예약했다."),

    # 861-880 (여가 / 화폐 / 추상 명사 / 통신)
    861: ("We packed tasty sandwiches and fruit for the family picnic.", "우리는 가족 소풍을 위해 맛있는 샌드위치와 과일을 챙겼다."),
    862: ("We pitched our tent and set up camp by the quiet lake.", "우리는 텐트를 치고 고요한 호숫가 옆에 야영지를 꾸렸다."),
    863: ("It is wise to save some money in the bank every month.", "매달 은행에 돈을 조금씩 저축하는 것은 현명한 일이다."),
    864: ("The souvenir postcard costs only one dollar.", "기념품 엽서의 가격은 단 1달러에 불과하다."),
    865: ("He found a shiny ten-cent coin on the sidewalk.", "그는 보도블록 위에서 반짝이는 10센트 동전을 하나 발견했다."),
    866: ("The subway fare in Seoul is around fourteen hundred won.", "서울 지하철 요금은 약 1,400원 정도이다."),
    867: ("Check the price tag before purchasing the jacket.", "재킷을 구매하기 전에 가격표를 확인하세요."),
    868: ("Living a healthy and active life brings true happiness.", "건강하고 활동적인 삶을 사는 것은 진정한 행복을 가져다준다."),
    869: ("The historic poem reflects deeply on love and death.", "그 역사적인 시는 사랑과 죽음에 대해 깊이 있게 성찰하고 있다."),
    870: ("Follow your dream and work persistently toward your goal.", "네 꿈을 따르고 목표를 향해 끈기 있게 노력해라."),
    871: ("We have high hope that our soccer team will win the trophy.", "우리는 우리 축구팀이 트로피를 들어 올릴 것이라는 큰 희망을 품고 있다."),
    872: ("Close your eyes and make a special birthday wish.", "눈을 감고 특별한 생일 소원을 빌어 보아라."),
    873: ("Good luck on your upcoming English vocabulary test!", "곧 있을 영어 단어 시험에서 좋은 결과가 있기를 행운을 빌어!"),
    874: ("Everyone desires to live in harmony and peaceful coexistence.", "모든 사람은 조화롭고 평화로운 공존 속에서 살기를 바란다."),
    875: ("The museum exhibit tells stories of courage during the war.", "박물관 전시는 전쟁 당시의 용기 있는 이야기들을 전해 준다."),
    876: ("Did you hear the exciting news about the science contest?", "과학 경시대회에 관한 신나는 소식 들었니?"),
    877: ("Grandfather reads the morning newspaper with his coffee.", "할아버지는 커피를 드시며 아침 신문을 읽으신다."),
    878: ("She bought an interesting science magazine at the bookstore.", "그녀는 서점에서 재미있는 과학 잡지를 한 권 샀다."),
    879: ("She wrote a sincere handwritten letter to her pen pal.", "그녀는 펜팔 친구에게 진심 어린 손편지를 썼다."),
    880: ("Check the mail box in the morning for postal deliveries.", "우편물이 도착했는지 아침에 우편함을 확인하세요."),

    # 881-900 (디지털 / 도형 / 속성)
    881: ("I sent an email to the teacher with my completed essay.", "나는 완성한 에세이를 첨부하여 선생님께 이메일을 보냈다."),
    882: ("Leave a brief message if I am unable to answer the phone.", "전화를 받을 수 없으면 짧은 메시지를 남겨 주세요."),
    883: ("He shared an inspiring post about his pet on social media.", "그는 소셜 미디어에 자신의 반려동물에 관한 감동적인 게시물을 공유했다."),
    884: ("Stick a postal stamp on the top right corner of the envelope.", "봉투 오른쪽 상단 모서리에 우표를 붙이세요."),
    885: ("The picture hanging on the gallery wall is colorful and bright.", "미술관 벽에 걸린 그림은 다채롭고 밝다."),
    886: ("She took a wonderful photo of the mountain sunset.", "그녀는 산 너머로 지는 일몰의 멋진 사진을 찍었다."),
    887: ("The peaceful sound of ocean waves helped me fall asleep.", "평화로운 파도 소리 덕분에 나는 잠에 스르륵 빠져들었다."),
    888: ("The loud construction noise outside woke me up early.", "밖에서 들려오는 요란한 공사 소음 때문에 아침 일찍 잠에서 깼다."),
    889: ("Turn on the bedside light so that you can read comfortably.", "편안하게 책을 읽을 수 있도록 침대 머리맡 스탠드를 켜세요."),
    890: ("The tall tree cast a long cooling shadow on the lawn.", "키 큰 나무가 잔디밭 위에 길고 시원한 그림자를 드리웠다."),
    891: ("Draw a straight line using your wooden ruler.", "나무자를 사용하여 곧은 직선을 그어라."),
    892: ("He made a good point during the classroom discussion.", "그는 교실 토론 중에 아주 좋은 요점을 지적했다."),
    893: ("The students sat in a big friendly circle on the rug.", "학생들은 양탄자 위에 둘러앉아 커다란 원을 만들었다."),
    894: ("A chess board consists of sixty-four black and white squares.", "체스판은 64개의 흑백 정사각형 칸으로 구성되어 있다."),
    895: ("What shoe size do you normally wear?", "보통 신발 사이즈를 몇으로 신으시나요?"),
    896: ("A ball has a round three-dimensional sphere shape.", "공은 둥근 3차원 구 모양을 띠고 있다."),
    897: ("The heavy parcel exceeded the allowed postal weight limit.", "그 무거운 소포는 허용된 우편 무게 제한을 초과했다."),
    898: ("The train traveled at high speed between the two cities.", "열차는 두 도시 사이를 고속으로 달렸다."),
    899: ("Could you tell me the best way to the central library?", "중앙도서관으로 가는 가장 좋은 길을 알려주시겠어요?"),
    900: ("Take one step at a time when climbing the steep stairs.", "가파른 계단을 오를 때는 한 번에 한 걸음씩 조심스럽게 디뎌라."),

    # 901-920 (사회 규칙 / 직업)
    901: ("Reading every night before bed is a wonderful habit.", "매일 밤 잠자리에 들기 전에 책을 읽는 것은 참 좋은 습관이다."),
    902: ("Every driver must obey the traffic safety rule.", "모든 운전자는 교통안전 규칙을 반드시 준수해야 한다."),
    903: ("The library books are arranged in alphabetical order.", "도서관 책들은 알파벳순으로 정돈되어 있다."),
    904: ("Taking off shoes indoors is an important Korean custom.", "실내에서 신발을 벗는 것은 한국의 중요한 풍습이다."),
    905: ("Learning to speak English well is a valuable life skill.", "영어로 유창하게 말하는 법을 배우는 것은 가치 있는 삶의 기술이다."),
    906: ("She loves her job as a children's book illustrator.", "그녀는 동화책 삽화가라는 자신의 직업을 무척 사랑한다."),
    907: ("Team members worked together to finish the assignment.", "팀원들은 과제를 마치기 위해 협력하여 일했다."),
    908: ("The factory worker operated the packaging machine carefully.", "공장 근로자는 포장 기계를 세심하게 조작했다."),
    909: ("Our team boss listened thoughtfully to our new project ideas.", "우리 팀장님은 새로운 프로젝트 아이디어를 사려 깊게 들어주셨다."),
    910: ("The historic king ruled the kingdom with wisdom and justice.", "역사 속의 그 왕은 지혜와 정의로 왕국을 다스렸다."),
    911: ("The elegant queen waved kindly to the cheering crowd.", "우아한 왕비가 환호하는 군중을 향해 다정하게 손을 흔들었다."),
    912: ("The young prince trained hard to become a brave leader.", "어린 왕자는 용감한 지도자가 되기 위해 열심히 훈련했다."),
    913: ("The fairytale princess wore a sparkling silver crown.", "동화 속 공주는 반짝이는 은빛 왕관을 쓰고 있었다."),
    914: ("The firefighter who saved the family was honored as a true hero.", "그 가족을 구한 소방관은 진정한 영웅으로 칭송받았다."),
    915: ("The police officer helped the lost child find his parents.", "경찰관은 길을 잃은 아이가 부모를 찾을 수 있도록 도와주었다."),
    916: ("The brave firefighter extinguished the flame rapidly.", "용감한 소방관이 불길을 신속하게 진화했다."),
    917: ("The experienced pilot landed the aircraft smoothly in the rain.", "숙련된 조종사가 빗속에서도 비행기를 부드럽게 착륙시켰다."),
    918: ("The courteous bus driver greeted each boarding passenger.", "친절한 버스 기사님은 탑승하는 모든 승객에게 다정하게 인사했다."),
    919: ("The head cook prepared delicious fresh pasta for the guests.", "수석 요리사가 손님들을 위해 신선하고 맛있는 파스타를 만들었다."),
    920: ("The hardworking farmer harvested golden wheat in autumn.", "부지런한 농부는 가을에 황금빛 밀을 수확했다."),

    # 921-940 (예술가 / 위험 / 에너지 / 물질)
    921: ("The talented singer performed a beautiful ballad on stage.", "재능 있는 가수가 무대 위에서 아름다운 발라드를 불렀다."),
    922: ("The ballet dancer leaped gracefully across the stage.", "발레 무용수가 무대 위를 우아하게 뛰어올랐다."),
    923: ("The popular actor delivered an emotional monologue in the movie.", "인기 배우가 영화 속에서 감동적인 독백 연기를 펼쳤다."),
    924: ("The acclaimed actress won a trophy for her starring role.", "호평을 받은 여배우가 주연상 트로피를 수상했다."),
    925: ("The local artist painted a colorful landscape of the harbor.", "지역 화가는 항구의 다채로운 풍경화를 그렸다."),
    926: ("The famous writer published an exciting mystery novel.", "그 유명한 작가는 흥미진진한 추리소설을 출간했다."),
    927: ("The scientist conducted an experiment in the chemistry lab.", "과학자는 화학 실험실에서 정밀한 실험을 진행했다."),
    928: ("The magician amazed the children with clever sleight of hand magic.", "마술사는 교묘한 손놀림 마술로 아이들을 놀라게 했다."),
    929: ("Drive carefully to prevent any minor traffic accident.", "경미한 교통사고라도 예방할 수 있도록 조심해서 운전하세요."),
    930: ("He had trouble solving the complex geometry problem.", "그는 복잡한 기하학 문제를 푸는 데 애를 먹었다."),
    931: ("The warning sign alerted hikers to the danger of falling rocks.", "경고 표지판이 등산객들에게 낙석의 위험을 알렸다."),
    932: ("Always wear a protective helmet for your safety while cycling.", "자전거를 탈 때는 안전을 위해 항상 보호 헬멧을 착용하세요."),
    933: ("We sat around the warm crackling camp fire at night.", "우리는 밤에 타닥타닥 타는 따뜻한 모닥불 주위에 둘러앉았다."),
    934: ("Gray smoke rose into the sky from the chimney.", "굴뚝에서 회색 연기가 하늘로 피어올랐다."),
    935: ("Eating balanced meals provides energy for the whole day.", "균형 잡힌 식사를 하면 하루 종일 쓸 수 있는 에너지가 생긴다."),
    936: ("Wind power generates clean renewable electricity.", "풍력 에너지는 깨끗하고 재생 가능한 전력을 생산한다."),
    937: ("Gravitational force pulls falling objects toward the ground.", "중력은 떨어지는 물체를 땅 쪽으로 끌어당긴다."),
    938: ("The kitchen stove runs safely on natural cooking gas.", "주방 가스레인지는 안전한 취사용 천연가스로 작동한다."),
    939: ("Add a few drops of olive oil to the fresh green salad.", "신선한 야채 샐러드에 올리브 오일 몇 방울을 둘러라."),
    940: ("The Olympic champion received a shining gold medal.", "올림픽 챔피언은 반짝이는 금메달을 목에 걸었다."),

    # 941-960 (물질 / 사물 / 표지)
    941: ("The old garden gate is made of sturdy wrought iron.", "오래된 정원 문은 튼튼한 무쇠 철로 만들어져 있다."),
    942: ("She wore a delicate silver necklace on her birthday.", "그녀는 생일에 섬세하고 고운 은목걸이를 걸었다."),
    943: ("Please sort and recycle plastic bottles responsibly.", "플라스틱병은 책임감을 가지고 분리수거해 주세요."),
    944: ("Handle the fragile glass bottle with great care.", "깨지기 쉬운 유리병은 각별히 주의해서 다루세요."),
    945: ("This sturdy rocking chair was carved from maple wood.", "이 튼튼한 흔들의자는 단풍나무 원목으로 조각되었다."),
    946: ("Write your ideas down on a clean sheet of paper.", "깨끗한 종이 한 장에 네 생각을 적어 보아라."),
    947: ("Pack the delicate ornaments carefully into a cardboard box.", "깨지기 쉬운 장식품들을 골판지 상자에 조심스럽게 포장해라."),
    948: ("Open a can of sweet corn to put in the salad.", "샐러드에 넣을 스위트콘 통조림 캔 하나를 따세요."),
    949: ("Tie the wooden boat securely to the dock with thick rope.", "굵은 밧줄로 나무 보트를 부두에 단단히 묶어라."),
    950: ("Tie a colorful string around the gift package.", "선물 포장 상자 주위에 알록달록한 끈을 묶으세요."),
    951: ("The school bell rang loudly to signal the end of class.", "수업 종료를 알리는 학교 종이 크게 울렸다."),
    952: ("The national flag fluttered proudly in the spring breeze.", "국기가 봄바람에 당당하게 펄럭였다."),
    953: ("Look at the road sign to see how far the city is.", "도시까지 거리가 얼마나 남았는지 도로 표지판을 보세요."),
    954: ("Make a check mark next to each completed task.", "완료한 항목 옆에는 체크 표시를 해 두세요."),
    955: ("Look both ways before walking across the pedestrian cross.", "보행자 횡단보도를 건너기 전에는 좌우를 모두 살피세요."),
    956: ("The little rabbit dug a cozy hole beneath the old tree.", "작은 토끼가 오래된 나무 아래에 아늑한 굴을 팠다."),
    957: ("Keep your transit card handy in your coat pocket.", "코트 주머니에 교통카드를 손쉽게 넣어 두어라."),
    958: ("A cozy bakery sits on the corner of the avenue.", "대로변 모퉁이에 아늑한 빵집이 하나 자리 잡고 있다."),
    959: ("Walk straight until you reach the far end of the hallway.", "복도 맨 끝에 다다를 때까지 똑바로 걸어가세요."),
    960: ("The race will start immediately after the countdown finishes.", "카운트다운이 끝나자마자 경주가 곧바로 시작될 것이다."),

    # 961-980 (자연 부위 / 일상 감탄사 / 인사)
    961: ("Walk on the right side of the sidewalk to allow room.", "지나갈 공간이 생기도록 보도의 오른쪽으로 걸으세요."),
    962: ("Don't stand too close to the sharp platform edge.", "날카로운 승강장 가장자리에 너무 가까이 서 있지 마세요."),
    963: ("Astronauts travel into outer space aboard rockets.", "우주비행사들은 로켓을 타고 머나먼 외우주로 여행한다."),
    964: ("Look up at the clear night sky filled with stars.", "별들이 총총하게 박힌 맑은 밤하늘을 올려다보아라."),
    965: ("The soccer team practiced drills on the school ground.", "축구팀은 학교 운동장에서 훈련을 거듭했다."),
    966: ("Dew drops sparkled on the green morning grass.", "아침의 푸른 잔디 위에 이슬방울이 영롱하게 반짝였다."),
    967: ("A single golden leaf drifted down from the maple tree.", "단풍나무에서 황금빛 나뭇잎 하나가 사뿐히 내려앉았다."),
    968: ("A cheerful little bird sang from the high tree branch.", "명랑한 작은 새 한 마리가 높은 나뭇가지 위에서 노래했다."),
    969: ("The deep root of the ancient tree anchors it against storms.", "고목의 깊은 뿌리는 폭풍우 속에서도 나무를 굳건히 지탱한다."),
    970: ("The rough bark of the pine tree protects it from insects.", "소나무의 거친 껍질은 곤충들로부터 나무를 보호해 준다."),
    971: ("Yes, I would love to join your badminton match.", "네, 당신의 배드민턴 경기에 정말 함께하고 싶어요."),
    972: ("No, there is no need to worry about the delay.", "아니요, 지연에 대해 걱정하실 필요가 전혀 없습니다."),
    973: ("I am not ready to leave for the station just yet.", "나는 아직 역으로 출발할 준비가 되지 않았다."),
    974: ("Oh, I completely forgot to bring my sketchbook.", "아, 내 스케치북 가져오는 것을 깜빡 잊었네."),
    975: ("Ah, now I finally understand how this puzzle works.", "아, 이제야 이 퍼즐이 어떻게 작동하는지 마침내 알겠어."),
    976: ("Wow, look at that magnificent rainbow in the sky!", "와, 하늘에 뜬 저 웅장하고 아름다운 무지개 좀 봐!"),
    977: ("Hi, it is great to see you again at school!", "안녕, 학교에서 너를 다시 만나서 정말 반가워!"),
    978: ("Hello, how can I assist you with your library account today?", "안녕하세요, 오늘 도서관 계정과 관련해 어떻게 도와드릴까요?"),
    979: ("Bye, see you tomorrow morning at soccer practice.", "잘 가, 내일 아침 축구 연습 때 보자."),
    980: ("Say goodbye to your classmates before you go home.", "집에 가기 전에 반 친구들에게 작별 인사를 나누세요."),

    # 981-1000 (태도 부사 / 양상 부사 - 정통 맥락 문장)
    981: ("Is everything okay with your homework assignment?", "숙제 과제는 별 탈 없이 잘 진행되고 있니?"),
    982: ("She speaks English remarkably well for a beginner.", "그녀는 초보자임에도 영어를 놀라울 정도로 잘한다."),
    983: ("Maybe we can visit the public art museum this weekend.", "어쩌면 이번 주말에 시립 미술관에 갈 수 있을지도 몰라."),
    984: ("Perhaps it will stop raining before our afternoon picnic.", "어쩌면 오후 소풍 전에 비가 그칠지도 모른다."),
    985: ("I really appreciate your kind help with my homework.", "내 숙제를 친절하게 도와주어서 진심으로 고마워."),
    986: ("This exciting film will surely entertain the entire family.", "이 흥미진진한 영화는 온 가족을 분명 즐겁게 해 줄 것이다."),
    987: ("I will certainly be there on time for the study meeting.", "스터디 모임에 반드시 제시간에 맞추어 가겠습니다."),
    988: ("It will probably be sunny and warm tomorrow morning.", "내일 아침에는 아마 날씨가 맑고 따뜻할 것이다."),
    989: ("I love all fruits, especially sweet juicy strawberries.", "나는 모든 과일을 좋아하지만, 특히 달콤하고 즙 많은 딸기를 좋아한다."),
    990: ("After studying hard all year, she finally passed the test.", "일 년 내내 열심히 공부한 끝에, 그녀는 마침내 시험에 합격했다."),
    991: ("The lights went out suddenly during the thunder storm.", "천둥 번개가 치는 도중에 불이 갑자기 꺼져 버렸다."),
    992: ("The ancient sea turtle swam slowly toward the deep water.", "오래된 바다거북이 깊은 물을 향해 천천히 헤엄쳐 갔다."),
    993: ("He quickly finished his breakfast so he wouldn't miss the bus.", "그는 버스를 놓치지 않으려고 아침 식사를 신속하게 마쳤다."),
    994: ("You can easily find the answer in chapter three of the book.", "책의 3장을 보면 정답을 쉽게 찾아낼 수 있다."),
    995: ("He was so tired that he could hardly keep his eyes open.", "그는 너무나 지쳐서 눈을 거의 뜨고 있을 수조차 없었다."),
    996: ("It took nearly two hours to reach the mountaintop.", "산 정상에 도달하는 데 거의 두 시간 가까이 걸렸다."),
    997: ("Please speak clearly into the microphone so all can hear.", "모두가 들을 수 있도록 마이크에 또렷하게 말씀해 주세요."),
    998: ("The students read their books quietly in the public library.", "학생들은 공공도서관에서 조용히 책을 읽었다."),
    999: ("The crowd cheered loudly when their soccer team scored.", "축구팀이 골을 넣자 관중들이 목청껏 크게 환호했다."),
    1000: ("The children smiled happily as they opened their birthday gifts.", "아이들은 생일 선물을 열어 보며 행복하게 활짝 웃었다."),
}
