# -*- coding: utf-8 -*-
"""
Level 1 정통 맞춤형 예문 데이터 Part 3 (단어 401 ~ 600)
초등/기초(A1~A2) 수준의 자연스러운 일상 회화 문장 및 매끄러운 한국어 번역
"""

PART3_SENTENCES = {
    # 401-420 (교통수단 / 자연 / 하늘)
    401: ("My dad drives an electric car to work.", "우리 아빠는 전기차를 운전해서 출근하신다."),
    402: ("I take the number seven bus to school.", "나는 7번 버스를 타고 등교한다."),
    403: ("The high-speed train arrived right on schedule.", "고속열차가 정시에 정확히 도착했다."),
    404: ("The subway is fast and convenient during rush hour.", "출퇴근 시간에는 지하철이 빠르고 편리하다."),
    405: ("We hailed a taxi because it started raining.", "비가 내리기 시작해서 우리는 택시를 잡았다."),
    406: ("A large delivery truck unloaded boxes in front of the store.", "커다란 배송 트럭이 가게 앞에 상자들을 내려놓았다."),
    407: ("The airplane soared smoothly above the clouds.", "비행기가 구름 위로 부드럽게 날아올랐다."),
    408: ("Our plane will land at Incheon Airport in thirty minutes.", "우리 비행기는 30분 뒤에 인천공항에 착륙합니다."),
    409: ("A rescue helicopter landed quickly on the hospital roof.", "구조 헬리콥터가 병원 옥상에 신속하게 착륙했다."),
    410: ("We rowed a small wooden boat across the peaceful lake.", "우리는 평화로운 호수를 가로질러 작은 나무 보트를 저었다."),
    411: ("A giant cruise ship sailed into the deep harbor.", "거대한 유람선이 깊은 항구 안으로 항해해 들어왔다."),
    412: ("There is heavy traffic on the highway this morning.", "오늘 아침 고속도로에 교통 체증이 심하다."),
    413: ("Show your concert ticket at the entrance.", "입구에서 콘서트 입장권을 보여주세요."),
    414: ("Please take your seat before the movie begins.", "영화가 시작하기 전에 자리에 앉아 주세요."),
    415: ("The bus stop is located right across the street.", "버스 정류장은 길 바로 건너편에 있다."),
    416: ("We pulled into a gas station to fill up the tank.", "우리는 기름을 채우기 위해 주유소로 들어갔다."),
    417: ("A bicycle has two wheels and pedals.", "자전거에는 바퀴 두 개와 페달이 있다."),
    418: ("We enjoyed spending a peaceful weekend close to nature.", "우리는 자연과 가까이에서 평화로운 주말을 보냈다."),
    419: ("The clear blue sky was dotted with white clouds.", "맑고 푸른 하늘에 하얀 구름이 둥실 떠 있었다."),
    420: ("The warm morning sun rose over the eastern mountains.", "따스한 아침 해가 동쪽 산 위로 떠올랐다."),

    # 421-440 (천체 / 날씨 / 지형)
    421: ("The bright full moon illuminated the dark path.", "밝은 보름달이 어두운 오솔길을 비추었다."),
    422: ("Countless stars twinkled brightly in the clear night sky.", "맑은 밤하늘에 수많은 별들이 밝게 반짝였다."),
    423: ("A dark rain cloud covered the afternoon sun.", "어두운 비구름이 오후의 햇살을 가렸다."),
    424: ("The sound of gentle rain falling on the roof is calming.", "지붕 위에 부드럽게 내리는 빗소리는 마음을 편안하게 해 준다."),
    425: ("Children love to build a cheerful snowman in the snow.", "아이들은 눈 속에서 유쾌한 눈사람 만드는 것을 좋아한다."),
    426: ("A gentle spring wind blew through the open window.", "부드러운 봄바람이 열린 창문 사이로 불어왔다."),
    427: ("Thick morning fog covered the lake and the bridge.", "짙은 아침 안개가 호수와 다리를 뒤덮었다."),
    428: ("The weather forecast warned of a severe winter storm.", "일기예보에서 매서운 겨울 폭풍을 경고했다."),
    429: ("Loud rumbling thunder shook the windows of the house.", "우르릉거리는 큰 천둥소리가 집 창문을 흔들었다."),
    430: ("A flash of bright lightning lit up the dark sky.", "번쩍하는 밝은 번개가 어두운 하늘을 밝혔다."),
    431: ("A colorful rainbow appeared in the sky after the rain stopped.", "비가 그친 후 하늘에 알록달록한 무지개가 나타났다."),
    432: ("Take a deep breath of fresh mountain air.", "신선한 산 공기를 깊이 들이마셔 보세요."),
    433: ("The Earth revolves around the sun once a year.", "지구는 1년에 한 번 태양 주위를 공전한다."),
    434: ("The airplane touched down safely on dry land.", "비행기가 마른 육지에 안전하게 착륙했다."),
    435: ("The dry ground was thirsty for spring rain.", "메마른 땅이 봄비를 간절히 기다리고 있었다."),
    436: ("The children made sand castles on the sunny beach.", "아이들이 햇살 가득한 해변에서 모래성을 쌓았다."),
    437: ("Wipe the dust off the bookshelf with a clean cloth.", "깨끗한 천으로 책장 위의 먼지를 닦아 내라."),
    438: ("His boots were covered in brown mud after the hike.", "등산을 마친 후 그의 장화는 갈색 진흙으로 뒤덮여 있었다."),
    439: ("We sat on a flat rock and enjoyed the mountain view.", "우리는 평평한 바위에 앉아 산 풍경을 감상했다."),
    440: ("He skipped a smooth stone across the surface of the pond.", "그는 매끄러운 돌을 연못 수면 위로 튕겼다."),

    # 441-460 (지형 / 식물 / 꽃)
    441: ("We climbed to the top of the mountain to watch the sunrise.", "우리는 일출을 보기 위해 산 정상에 올랐다."),
    442: ("The children rolled down the grassy green hill.", "아이들은 풀이 우거진 초록색 언덕을 굴러 내려왔다."),
    443: ("A clean river flows peacefully through the valley.", "깨끗한 강이 계곡 사이로 평화롭게 흐른다."),
    444: ("We rented a paddle boat and circled the quiet lake.", "우리는 오리배를 빌려 고요한 호수를 한 바퀴 돌았다."),
    445: ("We swam in the warm blue sea during our summer holiday.", "우리는 여름휴가 동안 따뜻하고 푸른 바다에서 수영을 했다."),
    446: ("Dolphins leaped gracefully out of the deep ocean waves.", "돌고래들이 깊은 바다 물결 위로 우아하게 뛰어올랐다."),
    447: ("Let's go for a walk along the sandy beach at sunset.", "일몰 무렵 모래사장을 따라 산책하러 가자."),
    448: ("Lighthouses guide ships safely along the rocky coast.", "등대는 바위투성이 해안을 따라 배들을 안전하게 안내한다."),
    449: ("Jeju is a famous volcanic island in South Korea.", "제주도는 한국의 유명한 화산섬이다."),
    450: ("Birds sang sweetly in the dense pine forest.", "울창한 소나무 숲에서 새들이 아름답게 지저귀었다."),
    451: ("This dining table is made of solid oak wood.", "이 식탁은 단단한 참나무 원목으로 만들어졌다."),
    452: ("We sat in the cool shade under a giant maple tree.", "우리는 거대한 단풍나무 아래 시원한 그늘에 앉았다."),
    453: ("Remember to water your house plant every few days.", "실내 화분에 며칠에 한 번씩 물 주는 것을 잊지 마세요."),
    454: ("Spring flowers bloom in vibrant yellow and pink colors.", "봄꽃들이 산뜻한 노란색과 분홍색으로 피어난다."),
    455: ("He gave his mother a fragrant red rose on her birthday.", "그는 어머니 생신에 향기로운 빨간 장미를 선물했다."),
    456: ("A green leaf fell gently from the tree onto the water.", "초록색 나뭇잎 하나가 나무에서 물 위로 사뿐히 떨어졌다."),
    457: ("Autumn leaves turn brilliant shades of red and gold.", "가을 낙엽은 눈부신 붉은빛과 황금빛으로 물든다."),
    458: ("Don't step on the freshly mowed green grass.", "새로 깎은 푸른 잔디를 밟지 마세요."),
    459: ("We planted a sunflower seed in a small terracotta pot.", "우리는 작은 토분 화분에 해바라기 씨앗을 심었다."),
    460: ("A little sparrow rested on a low tree branch.", "작은 참새 한 마리가 낮은 나뭇가지 위에 앉아 쉬었다."),

    # 461-480 (동물 / 반려동물 / 가축)
    461: ("The tree roots absorb water and nutrients from the soil.", "나무뿌리는 토양에서 물과 영양분을 흡수한다."),
    462: ("A lion is a powerful wild animal that lives in grasslands.", "사자는 초원에 사는 힘센 야생동물이다."),
    463: ("Taking care of a pet teaches children responsibility.", "반려동물을 돌보는 것은 아이들에게 책임감을 길러 준다."),
    464: ("The friendly dog wagged its tail when its owner arrived.", "친근한 강아지가 주인이 오자 꼬리를 흔들었다."),
    465: ("The playful puppy chewed on its rubber toy.", "장난기 많은 강아지가 고무 장난감을 씹으며 놀았다."),
    466: ("The sleepy cat curled up on the soft rug.", "잠이 솔솔 오는 고양이가 푹신한 양탄자 위에 웅크리고 누웠다."),
    467: ("The tiny kitten drank warm milk from a saucer.", "작은 아기 고양이가 접시에 담긴 따뜻한 우유를 마셨다."),
    468: ("A singing bird built a cozy nest in the cherry tree.", "노래하는 새 한 마리가 벚나무에 아늑한 둥지를 틀었다."),
    469: ("The mother chicken gathered her fluffy chicks around her.", "엄마 닭이 솜털 보송한 병아리들을 품 주위로 모았다."),
    470: ("The white duck paddled smoothly across the village pond.", "하얀 오리가 마을 연못 위를 유유히 헤엄쳐 건넜다."),
    471: ("A noisy goose honked loudly near the wooden gate.", "시끄러운 거위 한 마리가 나무 문 근처에서 크게 꽥꽥거렸다."),
    472: ("The brown horse galloped freely across the open meadow.", "갈색 말 한 마리가 넓은 초원을 자유롭게 질주했다."),
    473: ("The dairy cow grazed peacefully on sweet green pasture.", "젖소가 부드러운 풀밭에서 평화롭게 풀을 뜯었다."),
    474: ("The little pink pig rolled around happily in the pen.", "작은 분홍 돼지가 우리 안에서 신나게 뒹굴었다."),
    475: ("The fluffy white sheep followed the gentle shepherd.", "푹신한 흰 양들이 다정한 양치기를 따라갔다."),
    476: ("A nimble mountain goat stood perched on the rocky cliff.", "날렵한 산양이 바위 절벽 위에 우뚝 서 있었다."),
    477: ("A cute white rabbit hopped across the grassy lawn.", "귀여운 흰 토끼 한 마리가 잔디밭을 깡충깡충 뛰어갔다."),
    478: ("A tiny brown mouse nibbled on a crumb of bread.", "아주 작은 갈색 쥐 한 마리가 빵 부스러기를 갉아먹었다."),
    479: ("The clever rat found a way out of the wooden maze.", "영리한 쥐가 나무 미로를 빠져나갈 길을 찾아냈다."),
    480: ("The mischievous monkey swung swiftly from branch to branch.", "장난꾸러기 원숭이가 나뭇가지 사이를 휙휙 건너다녔다."),

    # 481-500 (야생동물 / 해양생물 / 곤충)
    481: ("The big black bear caught a fish in the rushing river.", "커다란 흑곰이 흐르는 강물에서 물고기 한 마리를 잡았다."),
    482: ("The proud lion rested under the shade of an acacia tree.", "위풍당당한 사자가 아카시아나무 그늘 아래서 휴식을 취했다."),
    483: ("The majestic Siberian tiger has distinctive striped fur.", "용맹한 시베리아호랑이는 독특한 줄무늬 털을 지니고 있다."),
    484: ("The giant elephant sprayed cool water with its long trunk.", "거대한 코끼리가 긴 코로 시원한 물을 뿜어냈다."),
    485: ("The tall giraffe reached the highest leaves on the tree.", "키가 큰 기린은 나무 맨 꼭대기의 잎사귀에 닿았다."),
    486: ("A zebra has unique black and white stripes across its body.", "얼룩말은 온몸에 독특한 흑백 줄무늬가 있다."),
    487: ("A mother kangaroo carries her tiny baby inside her pouch.", "엄마 캥거루는 주머니 속에 작은 아기를 넣고 다닌다."),
    488: ("The cuddly giant panda chewed happily on fresh bamboo.", "귀여운 대왕판다가 신선한 대나무를 맛있게 씹어 먹었다."),
    489: ("A sly red fox crept quietly through the tall forest grass.", "날렵한 붉은 여우가 울창한 숲 풀숲 사이를 조용히 기어갔다."),
    490: ("The lone gray wolf howled under the pale moonlight.", "외로운 회색 늑대가 창백한 달빛 아래서 길게 울부짖었다."),
    491: ("A graceful deer drank cool water from the mountain stream.", "우아한 사슴 한 마리가 산골짜기 시냇물에서 시원한 물을 마셨다."),
    492: ("A green garden snake slithered harmlessly between the rocks.", "초록색 뱀 한 마리가 바위틈 사이로 스르륵 미끄러져 갔다."),
    493: ("The little green frog jumped high from lily pad to lily pad.", "작은 초록색 개구리가 연잎 사이를 높이 폴짝폴짝 뛰어다녔다."),
    494: ("The ancient sea turtle swam slowly toward the warm shore.", "오래 산 바다거북이 따뜻한 해안을 향해 천천히 헤엄쳐 갔다."),
    495: ("The aquarium displayed many colorful tropical fish.", "수족관에는 알록달록한 열대어들이 많이 전시되어 있었다."),
    496: ("The blue whale is the largest mammal living on Earth.", "대왕고래는 지구상에 사는 가장 거대한 포유류이다."),
    497: ("The playful dolphin leaped high above the sparkling waves.", "장난꾸러기 돌고래가 반짝이는 파도 위로 높이 솟구쳐 올랐다."),
    498: ("The great white shark swam silently through the deep ocean.", "거대한 백상아리가 깊은 바닷속을 조용히 헤엄쳤다."),
    499: ("An insect typically has six legs and three body parts.", "곤충은 대개 여섯 개의 다리와 세 부분의 몸통을 가지고 있다."),
    500: ("A tiny ant can carry food much heavier than its own weight.", "작은 개미는 자기 몸무게보다 훨씬 무거운 먹이를 나를 수 있다."),

    # 501-520 (곤충 / 신체 / 색깔)
    501: ("The honey bee collected sweet nectar from blooming blossoms.", "꿀벌이 활짝 핀 꽃송이에서 달콤한 꿀을 모았다."),
    502: ("A graceful butterfly rested on a bright yellow flower.", "우아한 나비 한 마리가 밝은 노란색 꽃 위에 앉았다."),
    503: ("The clever spider spun a round silky web between the bushes.", "영리한 거미가 덤불 사이에 둥글고 비단 같은 거미줄을 쳤다."),
    504: ("Shoo away that buzzing fly from the kitchen table.", "식탁 주위에서 윙윙거리는 파리를 쫓아내라."),
    505: ("Apply bug spray so that mosquitoes don't bite you at night.", "밤에 모기에 물리지 않도록 모기 기피제를 바르세요."),
    506: ("The joyful puppy wagged its furry tail enthusiastically.", "신난 강아지가 털북숭이 꼬리를 힘차게 흔들었다."),
    507: ("The eagle spread its mighty wings and soared into the sky.", "독수리가 늠름한 날개를 활짝 펴고 하늘로 날아올랐다."),
    508: ("What is your favorite primary color?", "네가 가장 좋아하는 원색은 무엇이니?"),
    509: ("She wore a stylish red coat on Christmas Day.", "그녀는 크리스마스에 멋진 빨간색 코트를 입었다."),
    510: ("The calm blue sea stretched out as far as the eye could see.", "잔잔하고 푸른 바다가 눈이 닿는 곳까지 끝없이 펼쳐졌다."),
    511: ("Bright yellow sunflowers turned toward the warm sun.", "선명한 노란색 해바라기들이 따뜻한 태양을 향해 고개를 돌렸다."),
    512: ("The green tea fields looked vibrant in the early morning.", "이른 아침 녹차 밭 풍경이 싱그럽고 생기 있어 보였다."),
    513: ("He wore a sleek black suit to the graduation ceremony.", "그는 졸업식에 단정한 검은색 정장을 입었다."),
    514: ("Fresh white snow blanketed the quiet mountain village.", "깨끗한 하얀 눈이 조용한 산골 마을을 포근하게 덮었다."),
    515: ("She picked up a fallen brown acorn on the hiking trail.", "그녀는 등산로에서 떨어진 갈색 도토리 하나를 주웠다."),
    516: ("Dark gray storm clouds rolled across the afternoon sky.", "짙은 회색 먹구름이 오후 하늘을 가로질러 몰려왔다."),
    517: ("A bright orange traffic cone marked the road construction.", "눈에 띄는 주황색 교통 원뿔이 도로 공사 구역을 표시했다."),
    518: ("She bought a cute pastel pink notebook for journaling.", "그녀는 일기장으로 쓰려고 귀여운 파스텔 핑크 공책을 샀다."),
    519: ("The princess wore a rich purple velvet cape.", "공주는 기품 있는 보라색 벨벳 망토를 둘렀다."),
    520: ("The athlete won a prestigious gold medal in the competition.", "그 선수는 대회에서 영예로운 금메달을 획득했다."),

    # 521-540 (색깔 / 크기 / 물리적 특성)
    521: ("She polished her grandmother's antique silver spoon.", "그녀는 할머니의 앤티크 은숟가락을 반짝반짝 닦았다."),
    522: ("The morning sun was so bright that I had to squint.", "아침 햇살이 너무 밝아서 눈을 찌푸려야 했다."),
    523: ("It was too dark in the room to read without a lamp.", "방 안이 너무 어두워서 전등 없이는 책을 읽을 수 없었다."),
    524: ("This modern laptop is remarkably light and easy to carry.", "이 최신 노트북은 놀라울 정도로 가볍고 들고 다니기 편하다."),
    525: ("An elephant is a remarkably big land animal.", "코끼리는 눈에 띄게 커다란 육상 동물이다."),
    526: ("The library has a large collection of classic literature.", "그 도서관은 고전 문학에 관한 방대한 장서를 보유하고 있다."),
    527: ("She lives in a cozy small apartment near the park.", "그녀는 공원 근처의 아늑하고 작은 아파트에 산다."),
    528: ("The little boy clapped his hands with joy.", "어린 소년이 기쁨에 겨워 손뼉을 쳤다."),
    529: ("A tiny hummingbird hovered next to the blooming rose.", "아주 작은 벌새 한 마리가 활짝 핀 장미 옆에서 맴돌았다."),
    530: ("A huge cargo ship entered the bustling international port.", "거대한 화물선 한 척이 번잡한 국제 항구로 입항했다."),
    531: ("It was a long journey across the country by train.", "기차를 타고 전국을 횡단하는 것은 긴 여정이었다."),
    532: ("Take a short break to rest your eyes after studying.", "공부를 마친 후에는 눈을 쉬게 하기 위해 짧은 휴식을 취하세요."),
    533: ("He is the tallest basketball player on the school team.", "그는 학교 농구팀에서 키가 가장 큰 선수이다."),
    534: ("The eagle flew high above the snow-capped mountain peaks.", "독수리는 눈 덮인 산봉우리 위를 높이 날았다."),
    535: ("Keep your voice low in the hospital hallway.", "병원 복도에서는 목소리를 낮춰 주세요."),
    536: ("Dolphins can dive into very deep ocean water.", "돌고래는 바닷속 아주 깊은 곳까지 잠수할 수 있다."),
    537: ("Young children should play only in the shallow end of the pool.", "어린이들은 수영장의 얕은 구역에서만 놀아야 한다."),
    538: ("The wide boulevard was lined with tall cherry blossom trees.", "넓은 대로는 키 큰 벚나무들로 줄지어 늘어서 있었다."),
    539: ("A narrow stone path wound through the old village.", "좁은 돌길이 오래된 마을 사이로 굽이쳐 이어졌다."),
    540: ("She wrapped a thick woolen blanket around her shoulders.", "그녀는 어깨에 두꺼운 양모 담요를 둘렀다."),

    # 541-560 (촉감 / 온도 / 맛)
    541: ("He sliced a thin piece of cheddar cheese for the cracker.", "그는 크래커 위에 올릴 얇은 체더치즈 한 조각을 썰었다."),
    542: ("The chubby cat became fat because it loved treats.", "통통한 고양이는 간식을 너무 좋아해서 살이 쪘다."),
    543: ("The box was far too heavy for one person to lift.", "그 상자는 혼자서 들기에는 너무 무거웠다."),
    544: ("Be careful, the soup pot on the stove is very hot.", "조심해, 가스레인지 위의 국 냄비가 매우 뜨거워."),
    545: ("We drank warm herbal tea beside the crackling fireplace.", "우리는 타닥타닥 타는 난로 곁에서 따뜻한 허브차를 마셨다."),
    546: ("A cool breeze felt refreshing after a long jog.", "오래 달리고 난 후에 부는 시원한 산들바람은 상쾌했다."),
    547: ("Put on your gloves because it is freezing cold outside.", "밖이 얼어붙을 듯이 추우니 장갑을 끼어라."),
    548: ("Hang your wet laundry outside in the warm dry breeze.", "젖은 빨래를 따뜻하고 건조한 바람 부는 야외에 널어라."),
    549: ("Her shoes were completely wet after stepping in the puddle.", "웅덩이를 밟는 바람에 그녀의 신발이 흠뻑 젖었다."),
    550: ("Always keep your study room tidy and clean.", "공부방은 항상 정돈되고 깨끗하게 유지해라."),
    551: ("Wash the dirty dishes in the kitchen sink.", "싱크대에 있는 더러운 그릇들을 설거지해라."),
    552: ("We picked fresh juicy strawberries straight from the farm.", "우리는 농장에서 갓 딴 신선하고 즙 많은 딸기를 골랐다."),
    553: ("Ripe honeydew melon tastes wonderfully sweet and refreshing.", "잘 익은 멜론은 기분 좋게 달콤하고 시원한 맛이 난다."),
    554: ("Dark unsweetened cocoa powder has a naturally bitter taste.", "설탕이 안 들어간 다크 코코아 가루는 본래 쌉싸름한 맛이 난다."),
    555: ("Fresh lemon juice adds a pleasantly sour flavor to the drink.", "신선한 레몬즙은 음료에 기분 좋은 새콤한 맛을 더해 준다."),
    556: ("These potato chips are a little too salty for me.", "이 감자칩은 내 입맛에는 조금 너무 짜다."),
    557: ("Mom made a delicious pot of chicken noodle soup.", "엄마가 맛있는 치킨 누들 수프 한 냄비를 끓여 주셨다."),
    558: ("He studied hard and earned high marks on the test.", "그는 열심히 공부해서 시험에서 높은 점수를 받았다."),
    559: ("This soft goose-down pillow provides great neck support.", "이 푹신한 거위털 베개는 목을 편안하게 받쳐 준다."),
    560: ("The bark on the old pine tree felt coarse and rough.", "오래된 소나무 껍질은 거칠고 투박하게 느껴졌다."),

    # 561-580 (질감 / 속도 / 성격 / 외모)
    561: ("The surface of the polished marble floor was glassy and smooth.", "윤이 나는 대리석 바닥 표면은 유리처럼 매끄러웠다."),
    562: ("Keep sharp scissors away from small toddlers.", "날카로운 가위는 어린 유아들의 손이 닿지 않는 곳에 두세요."),
    563: ("Cheetahs are famous for running remarkably fast.", "치타는 놀라울 정도로 빠르게 달리는 것으로 유명하다."),
    564: ("He gave a quick nod to show he understood the message.", "그는 메시지를 이해했다는 뜻으로 가볍게 고개를 끄덕였다."),
    565: ("The slow turtle crossed the garden lawn inch by inch.", "느린 거북이가 정원 잔디밭을 한 치씩 천천히 기어갔다."),
    566: ("He woke up early to catch the first morning train.", "그는 아침 첫차를 타기 위해 일찍 일어났다."),
    567: ("Hurry up or we will be late for the movie.", "서두르지 않으면 영화에 늦을 거야."),
    568: ("She bought a brand new backpack for the school semester.", "그녀는 새 학기를 맞아 완전 새 책가방을 샀다."),
    569: ("The historic village has many old traditional tiled houses.", "그 역사적인 마을에는 오래된 전통 기와집이 많이 있다."),
    570: ("The young students listened attentively to the speech.", "어린 학생들이 강연에 귀를 쫑긋 세우고 집중했다."),
    571: ("Eating green vegetables and exercising is good for your body.", "채소를 먹고 운동하는 것은 몸에 참 좋다."),
    572: ("Have a nice weekend with your family and friends.", "가족, 친구들과 함께 즐거운 주말 보내세요."),
    573: ("We had a great time celebrating grandmother's birthday.", "우리는 할머니의 생신을 축하하며 아주 멋진 시간을 보냈다."),
    574: ("Thank you for asking, I am doing fine today.", "물어봐 주셔서 감사합니다, 저는 오늘 아주 잘 지내고 있어요."),
    575: ("Don't eat expired food because it is bad for your health.", "유통기한이 지난 음식은 건강에 나쁘니 먹지 마세요."),
    576: ("A terrible traffic jam delayed all the airport buses.", "끔찍한 교통 체증으로 모든 공항버스가 지연되었다."),
    577: ("The sunset over the ocean horizon was truly beautiful.", "바다 수평선 너머로 지는 일몰은 참으로 아름다웠다."),
    578: ("She wore a pretty floral dress with white lace.", "그녀는 흰 레이스가 달린 예쁜 꽃무늬 원피스를 입었다."),
    579: ("The cute puppy curled up and fell fast asleep.", "귀여운 강아지가 몸을 웅크리고 새근새근 잠이 들었다."),
    580: ("The handsome actor smiled warmly at the waiting fans.", "잘생긴 배우가 기다리던 팬들에게 다정하게 미소를 지었다."),

    # 581-600 (성품 / 지능 / 상태 / 안전)
    581: ("The fairytale story tells of the ugly duckling becoming a swan.", "그 동화는 미운 오리 새끼가 백조가 되는 이야기를 들려준다."),
    582: ("She is a smart student who solves tricky math puzzles quickly.", "그녀는 까다로운 수학 퍼즐을 척척 풀어내는 똑똑한 학생이다."),
    583: ("The clever dog figured out how to open the door latch.", "영리한 강아지가 문빗장을 여는 방법을 알아냈다."),
    584: ("King Solomon was known across the land as a wise ruler.", "솔로몬 왕은 지혜로운 군주로 온 나라에 널리 알려졌다."),
    585: ("It was foolish to go hiking in a heavy snowstorm.", "거센 눈보라 속에서 등산을 가는 것은 어리석은 짓이었다."),
    586: ("Don't waste time arguing over such stupid little things.", "그런 바보 같고 사소한 일로 다투며 시간을 낭비하지 마라."),
    587: ("The kind nurse brought extra warm blankets to the patient.", "친절한 간호사 선생님이 환자에게 따뜻한 담요를 더 가져다주셨다."),
    588: ("He spoke to the nervous child in a gentle and soft tone.", "그는 불안해하는 아이에게 다정하고 부드러운 어조로 말을 건넸다."),
    589: ("The brave firefighter entered the burning building to save lives.", "용감한 소방관이 생명을 구하기 위해 불타는 건물 안으로 들어갔다."),
    590: ("Daily weight training made his arms remarkably strong.", "매일 한 웨이트 트레이닝 덕분에 그의 팔 힘이 눈에 띄게 강해졌다."),
    591: ("The sick kitten was too weak to stand on its paws.", "아픈 아기 고양이는 발로 서 있기조차 너무 힘이 없었다."),
    592: ("The generous rich philanthropist donated funds to build a school.", "마음씨 넉넉한 부유한 자선가가 학교 설립 기금을 기부했다."),
    593: ("The charitable organization provides warm meals to poor families.", "그 자선단체는 형편이 어려운 가정에 따뜻한 식사를 제공한다."),
    594: ("The doctor is busy consulting patients throughout the day.", "의사 선생님은 하루 종일 환자들을 진료하느라 바쁘시다."),
    595: ("Feel free to ask any questions if something is unclear.", "이해가 잘 안되는 부분이 있으면 언제든 편하게 질문하세요."),
    596: ("The public library is a quiet place where people read books.", "공공도서관은 사람들이 책을 읽는 조용한 장소이다."),
    597: ("A loud clap of thunder startled everyone in the room.", "요란한 천둥소리가 방 안에 있던 모든 사람을 깜짝 놀라게 했다."),
    598: ("The street market became lively and noisy with crowds.", "재래시장은 인파로 붐비며 활기차고 시끌벅적해졌다."),
    599: ("Fasten your seatbelt so that you are completely safe in the car.", "차 안에서 완전히 안전하도록 안전벨트를 매세요."),
    600: ("It is extremely dangerous to swim in deep rough ocean currents.", "깊고 거친 바다 해류에서 수영하는 것은 매우 위험하다."),
}
